### ISSUE TITLE
内存占用偏高

### ISSUE THREAD

**Issue by duckie8** [alibaba-cloud-toolkit/cosy#10]
![image](https://user-images.githubusercontent.com/16376759/142986717-b48a4c32-b896-45e4-b1d5-f171bd4a3c5b.png)
是这个插件的进程吧？

**Comment by HaoboGu** [comment]
你好，是的。目前版本多开IDE之后，会启动多个补全实例。这个问题我们已经识别到了，会在近期修复~

**Comment by duckie8** [comment]
嗯嗯，而且实际使用体验感觉没有codota那么顺滑，使用久了很容易卡顿（不知是否这个插件的原因

**Comment by HaoboGu** [comment]
在下一版插件中，我们会修复一些可能导致卡顿的问题。我们现在在测试中，感觉上流畅度提升还是比较明显的。欢迎届时体验反馈哈😁

**Comment by zengyao0831** [comment]
期待修复!!!是真的卡,而且不区分大小写真的很麻烦

**Comment by zxdxjtu** [comment]
@duckie8 @zengyao0831 0.10.1-beta版本正式上线啦，针对内存问题做了缩减优化，在多开IDE的情况下只会启动一个后台进程。并且针对反馈较多的大小写问题，增加了大小写模糊匹配的功能。另外这个版本增加了StackOverflow问答搜索，可以在插件内部通过API或中英文自然语言描述搜索问答，欢迎体验。
