### ISSUE TITLE
搜索出来的代码示例 点击跳转到源详情 github 会出现404

### ISSUE THREAD

**Issue by 0x-newe** [alibaba-cloud-toolkit/cosy#100]
**Describe the bug（描述您遇到的问题）**

搜索出来的代码示例 点击跳转到源详情 github 会出现404 原因是截图红框内多出来的 url 路径导致的，如下图所示，手动删除多余的路径就可以打开了。

**To Reproduce（复现步骤）**

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/3862575/174992747-f1548ea0-03be-41af-a08d-d61ca4c66b67.png)

![image](https://user-images.githubusercontent.com/3862575/174993116-7f0b8c6c-fe9c-4fed-935b-89662d8f83ae.png)

![image](https://user-images.githubusercontent.com/3862575/174993253-053337ce-167e-4bc5-966e-735a94b67182.png)

**System（本地系统）**
 - OS: windows 11
 - Cosy Version: Alibaba Cloud Al Coding Assistant 0.10.3-beta

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
该问题已修复，非常感谢反馈
