### ISSUE TITLE
虚拟机环境中无法搜索

### ISSUE THREAD

**Issue by zhenkuroro** [alibaba-cloud-toolkit/cosy#101]
在虚拟机中的IDEA安装后，无论如何都搜索不到内容。本机中可以正常搜索代码。

**System（本地系统）**
 - OS: win11专业版
 - Cosy Version: 0.10.3

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
1215953586@qq.com

**Comment by Yuyang105** [comment]
请问虚拟机网络环境正常么，可以访问外网？另外，麻烦提供下 cosy.log日志

Windows用户：C盘/用户/[用户名]/.cosy/logs

**Comment by Yuyang105** [comment]
另外麻烦检查下虚拟机的系统时间设置是否准确，我们会根据时间戳做安全校验，有可能是这个原因导致的
