### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by hekang-bigdata** [alibaba-cloud-toolkit/cosy#104]
**Describe the bug（描述您遇到的问题）**
无法搜索  代码没有提示

**To Reproduce（复现步骤）**
无法搜索  代码没有提示 重启和重新安装也没有效果

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/62013888/176576110-99fe56c5-8c42-4330-8b11-e8b9215a1b88.png)

**System（本地系统）**
 - OS:  win11
 - Cosy Version:  0.10.2-beta

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
hekang_14@163.com

**Comment by hekang-bigdata** [comment]
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/9015777/cosy.log)

**Comment by zxdxjtu** [comment]
麻烦提供下idea的日志呢，在上方工具栏 Help > Show log in Finder

**Comment by zxdxjtu** [comment]
请问下你现在的cosy版本是多少？最新版本是0.10.3.2-beta

**Comment by hekang-bigdata** [comment]
> 请问下你现在的cosy版本是多少？最新版本是0.10.3.2-beta

版本在问题中写了 ，日志 在回答中上传了
![image](https://user-images.githubusercontent.com/62013888/176577614-14252c41-3d5c-4328-b294-783363b41c3a.png)
通过idea下载的就是0.10.2-beta版本

**Comment by hekang-bigdata** [comment]
> 



> 麻烦提供下idea的日志呢，在上方工具栏 Help > Show log in Finder
[idea.log](https://github.com/alibaba-cloud-toolkit/cosy/files/9015839/idea.log)

**Comment by zxdxjtu** [comment]
请升级一下cosy版本到0.10.3.2-beta，这个问题我们应该已经修复过
