### ISSUE TITLE
自动补全无法使用

### ISSUE THREAD

**Issue by mmcLine** [alibaba-cloud-toolkit/cosy#105]
**自动补全无法使用**

我安装之后无法使用自动补全，搜索代码正常使用。
![image](https://user-images.githubusercontent.com/37876129/176655395-63aaf5a3-e42c-4f01-8377-f5f2e21eabe3.png)

windows系统，IDEA2020.1

[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/9018931/cosy.log)

我的邮箱：990974807@qq.com

**Comment by zxdxjtu** [comment]
请确认下cosy的版本，最新版本是0.10.3.2-beta，
可以试一下关闭cosy进程，删除.cosy目录，然后重启idea，如果仍然没有补全，麻烦提供下cosy.log同目录下的cosy.local日志

**Comment by mmcLine** [comment]
哦哦，我的idea好像不支持最新的。我试试升级我的idea版本试试

**Comment by mmcLine** [comment]
我的idea目前只支持0.10.2-beta版本，这个版本可以使用吗

**Comment by zxdxjtu** [comment]
为了支持更好的搜索体验，我们最新的版本要求idea2020.3以上，您看到最新版本只有0.10.2-beta应该是因为idea版本过低，麻烦升级下Idea版本，并且升级下cosy
