### ISSUE TITLE
没有搜索框

### ISSUE THREAD

**Issue by IT-BaiSir** [alibaba-cloud-toolkit/cosy#106]
**Describe the bug（描述您遇到的问题）**

**To Reproduce（复现步骤）**

![image](https://user-images.githubusercontent.com/94953651/177458419-92701a75-41da-4c02-a9eb-07125854ea26.png)

**Screenshots（截图）**

**System（本地系统）**
 - OS: win10
 - Cosy Version: 0.10.3.2-beta

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
麻烦确认下补全是否正常，cosy进程是否存在。
另外麻烦提供下日志信息：

cosy日志：
Mac用户：~/.cosy/logs
Windows用户：C盘/用户/[用户名]/.cosy/logs

idea日志：
工具栏：Help > Show log in Finder

**Comment by IT-BaiSir** [comment]
> 麻烦确认下补全是否正常，cosy进程是否存在。 另外麻烦提供下日志信息：
> 补全正常
> cosy日志： Mac用户：~/.cosy/logs Windows用户：C盘/用户/[用户名]/.cosy/logs
> [cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/9051130/cosy.log)

> idea日志： 工具栏：Help > Show log in Finder

**Comment by zxdxjtu** [comment]
亲，看现象是本地缺少代码补全的推理环境，导致cosy启动失败，可以参考这个FAQ检查下本地系统缺少什么dll文件，然后尝试安装并重启idea：https://alibaba-cloud-toolkit.github.io/cosy/#/zh-cn/guide/faq?id=q-%e4%bb%a3%e7%a0%81%e8%a1%a5%e5%85%a8%e6%97%a0%e7%bb%93%e6%9e%9c%e6%80%8e%e4%b9%88%e5%8a%9e%ef%bc%9f

下个版本我们打包时会尽量避免windows系统的依赖，从而从根本上解决这类问题
