### ISSUE TITLE
图标显示不正确

### ISSUE THREAD

**Issue by ZhiJian-Wang** [alibaba-cloud-toolkit/cosy#11]
![image](https://user-images.githubusercontent.com/93644197/143236248-086b67d5-17ed-4826-80f9-2bc115ed554d.png)
如题，图标过大

**Comment by zxdxjtu** [comment]
感谢反馈，我们会在下周整体评估视觉体验设计，这个问题会排期修复。

**Comment by HaoboGu** [comment]
已经在0.9.6-beta版本中修复，请更新至最新版本~
