### ISSUE TITLE
期待可以用到pycharm上

### ISSUE THREAD

**Issue by MeditatorV** [alibaba-cloud-toolkit/cosy#110]
**Please describe the feature you request（请描述您的需求）**

**Describe the solution you'd like （请描述您的解法）**

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by MeditatorV** [comment]
> 请问您是想在PyCharm上使用补全还是搜索？PyCharm的补全我们正在开发，即将在下个版本发布，敬请期待

希望可以补全

**Comment by zxdxjtu** [comment]
您好，0.10.4-beta版本已发布，兔年之际支持语言也变two了，支持了PyCharm端的Python语言补全，欢迎体验。
