### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by wangkz959** [alibaba-cloud-toolkit/cosy#116]
**Describe the bug（描述您遇到的问题）**
之前一段时间能用，现在无法搜索，代码没有提示

**To Reproduce（复现步骤）**
日志文件
[idea.log](https://github.com/alibaba-cloud-toolkit/cosy/files/9238319/idea.log)
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/9238320/cosy.log)

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/92144310/182271791-56c7e387-d72d-4beb-8d9f-a0c0bcf4d3f1.png)
![image](https://user-images.githubusercontent.com/92144310/182270533-f5ce02c1-c014-43c9-8903-246de781caf8.png)

**System（本地系统）**
 - OS:
![image](https://user-images.githubusercontent.com/92144310/182270746-0e1d6ce9-4531-4255-b646-152a499befe2.png)
 - Cosy Version: 
![image](https://user-images.githubusercontent.com/92144310/182270582-ddb29e82-2c78-46d7-97aa-cdc50d1b6676.png)

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
貌似是本地数据库的问题，烦请把cosy进程杀死，然后删除.cosy目录，重启IDEA，应该能解决

**Comment by wangkz959** [comment]
按步骤操作后，已解决问题。为效率点赞。
