### ISSUE TITLE
请问何时支持JavaScript以及python呢？

### ISSUE THREAD

**Issue by AWeiIsCoding** [alibaba-cloud-toolkit/cosy#118]
期待支持JavaScript以及python，因为实在是太好用了！！赞！！

想知道大概的上线时间

iszlw@foxmail.com

**Comment by HaoboGu** [comment]
Python版本已经在测试中了。JavaScript版本目前没有预估上线时间 😢

**Comment by AWeiIsCoding** [comment]
嗯嗯好！！ 期待期待！
