### ISSUE TITLE
插件方法提示应该根据方法参数多少来给出对应的提示

### ISSUE THREAD

**Issue by mxsm** [alibaba-cloud-toolkit/cosy#12]
![image](https://user-images.githubusercontent.com/15797831/143372185-3559a135-3b4b-4d3a-8378-0ea818f9fb3e.png)
实际提示是：MDC.put("");
希望提示是： MDC.put("","");

**Comment by HaoboGu** [comment]
你好，感谢反馈！这个问题我们研究下，看看有没有比较好的解决方案

**Comment by mxsm** [comment]
> 你好，感谢反馈！这个问题我们研究下，看看有没有比较好的解决方案

还有，cosy插件给出的提示后面返回类型能不能不是Cosy而是相对应的类型，前面的图标就能区分是不是Cosy插件了。后面提示给出相对应的类型能够更好的让开发者选择对应的是方法。要不然选错了就要去修改还是比较麻烦和不是那么的友好

**Comment by HaoboGu** [comment]
> 还有，cosy插件给出的提示后面返回类型能不能不是Cosy而是相对应的类型，前面的图标就能区分是不是Cosy插件了。后面提示给出相对应的类型能够更好的让开发者选择对应的是方法。要不然选错了就要去修改还是比较麻烦和不是那么的友好

感谢反馈，这是很好的建议，但是当前实现起来还略有难度。我们这边先记录一下，后续会投入尝试解决这个问题

**Comment by zxdxjtu** [comment]
该问题已在0.9.6-beta版本修复，欢迎升级体验✅
