### ISSUE TITLE
插件怎么汉化，国人插件看英文不爽啊

### ISSUE THREAD

**Issue by fishnolater** [alibaba-cloud-toolkit/cosy#121]
![image](https://user-images.githubusercontent.com/53165052/185290101-76596a76-1556-4b83-a201-17b459552468.png)
![image](https://user-images.githubusercontent.com/53165052/185290154-8e7fa5a0-34f3-465c-a7f9-82df13c982b3.png)
前面的钩呢

**Comment by zhangyukun230** [comment]
中英文适配是自适应系统的，将系统环境改简体中文环境即可。
