### ISSUE TITLE
没法联网,只要写代码就会显示更新

### ISSUE THREAD

**Issue by Hehebulu** [alibaba-cloud-toolkit/cosy#122]
**Describe the bug（描述您遇到的问题）**没法联网,只要写代码就会显示更新

**To Reproduce（复现步骤）** 没法联网,只要写代码就会显示更新

**Screenshots（截图）**

**System（本地系统）** window 10
 - OS: 
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
麻烦看一下我们的问题排查步骤，提供一下版本号和日志，可以尝试自助修复一下
https://github.com/alibaba-cloud-toolkit/cosy/issues/115

**Comment by Hehebulu** [comment]
删除用户路径下.cosy文件夹后重启IDEA后问题得以解决,感谢










在 2022-08-24 11:09:56，"Zhang Xindong" ***@***.***> 写道：

麻烦看一下我们的问题排查步骤，提供一下版本号和日志，可以尝试自助修复一下
#115
