### ISSUE TITLE
搜索不到任何结果

### ISSUE THREAD

**Issue by wupengwei** [alibaba-cloud-toolkit/cosy#126]
Mac 版本：12.4
idea版本：2022.1.2（Ultimate Edition）
插件版本：0.10.3.2-beta
<img width="489" alt="图片" src="https://user-images.githubusercontent.com/11818275/187860805-83e9b1c8-54cf-4362-b86b-cd18cf381336.png">

**Comment by zxdxjtu** [comment]
建议根据faq排查一下：https://github.com/alibaba-cloud-toolkit/cosy/blob/main/docs/zh-cn/guide/faq.md

不行的话，ping codeup.cn-hangzhou.aliyuncs.com试试网络连接，或者下载all-in-one离线版

**Comment by wupengwei** [comment]
找到原因了，通过查看~/.cosy/logs异常日志 发现 ：我本地host没有配置 127.0.0.1 localhost
配置host后，重启idea ，可以用了
