### ISSUE TITLE
不提示补全 疯狂吃电脑内存

### ISSUE THREAD

**Issue by manchesterstoke** [alibaba-cloud-toolkit/cosy#127]
**Describe the bug（描述您遇到的问题）**
某天cosy突然不提示补全  每次打代码就在疯狂加载导致IDEA卡顿

**To Reproduce（复现步骤）**

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/33923008/189843274-d531472b-f998-4ea2-8a28-50da02c7fb87.png)

**System（本地系统）**
 - OS: Windows11 Pro
 - Cosy Version: 0.10.3.2-beta

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
nasemitsuki@outlook.jp

**Comment by zxdxjtu** [comment]
抱歉给你带来了不好的体验，麻烦根据操作步骤发我们日志排查下：https://github.com/alibaba-cloud-toolkit/cosy/issues/115
可以试一下，kill掉cosy进程，删除~/.cosy目录，然后重启IDEA

**Comment by manchesterstoke** [comment]
I appreciate you replying so fast.
按照FAQ里面的尝试了一遍，解决了问题。
