### ISSUE TITLE
为什么我的idea一用这个后台一直更新他

### ISSUE THREAD

**Issue by 2497296400** [alibaba-cloud-toolkit/cosy#128]
**Describe the bug（描述您遇到的问题）**

**To Reproduce（复现步骤）**

**Screenshots（截图）**
![1663248683977](https://user-images.githubusercontent.com/97862323/190416992-07e892c2-c333-4c58-b2d5-2229782e70b8.jpg)

**System（本地系统）**
 - OS: 
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by HaoboGu** [comment]
Hi, 你可以尝试按照我们的FAQ排查一下：https://github.com/alibaba-cloud-toolkit/cosy/blob/main/docs/zh-cn/guide/faq.md

或者可以试一下，kill掉cosy进程，删除~/.cosy目录，然后重启IDEA

**Comment by zxdxjtu** [comment]
需要更多信息，如faq无法解决，请再次联系
