### ISSUE TITLE
idea 新版本不兼容

### ISSUE THREAD

**Issue by lihongchun** [alibaba-cloud-toolkit/cosy#13]

**Comment by zxdxjtu** [comment]
请问您的版本是什么？EAP版本吗？

**Comment by wushuangcoder** [comment]
Plugin 'Alibaba Cloud AI Coding Assistant' (version '0.9.3-beta') is not compatible with the current version of the IDE, because it requires build 212.* or older but the current build is IU-213.5744.223

**Comment by lihongchun** [comment]
2021.3

**Comment by HaoboGu** [comment]
收到，我们会尽快兼容掉

**Comment by zxdxjtu** [comment]
您好，新版本支持213版本，离线包已更新至https://github.com/alibaba-cloud-toolkit/cosy/releases/tag/0.9.5-beta
插件市场正在审核中，即将生效。
