### ISSUE TITLE
代码文档搜索bug

### ISSUE THREAD

**Issue by maozhiya** [alibaba-cloud-toolkit/cosy#131]
**Describe the bug（描述您遇到的问题）**
代码文档搜索第一次能搜索，之后就搜索不到任何内容了

**To Reproduce（复现步骤）**

**Screenshots（截图）**

![image](https://user-images.githubusercontent.com/84663932/193194228-824465a9-4768-4ba3-ac5a-b13dd08c3be3.png)

**System（本地系统）**
 - OS: windows10
 - Cosy Version: 最新版本

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
2162862955@qq.com

**Comment by HaoboGu** [comment]
你好，可否按照[这里](https://github.com/alibaba-cloud-toolkit/cosy/issues/115)的步骤看能否解决问题，如果没能解决问题，麻烦上传一下日志我们排查一下

**Comment by zxdxjtu** [comment]
需要更多信息，如faq无法解决，请再次联系
