### ISSUE TITLE
我现在所在的公司，在内网无法使用

### ISSUE THREAD

**Issue by KristenZB** [alibaba-cloud-toolkit/cosy#132]
**Please describe the feature you request（请描述您的需求）**

**Describe the solution you'd like （请描述您的解法）**

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by HaoboGu** [comment]
在内网环境下，可以参考[这里](https://alibaba-cloud-toolkit.github.io/cosy/#/zh-cn/guide/quickstart)，使用离线all-in-one包

**Comment by KristenZB** [comment]
你邮件已收到，我将尽快回复       
         【校外联周斌】

**Comment by KristenZB** [comment]
你邮件已收到，我将尽快回复       
         【校外联周斌】
