### ISSUE TITLE
cosy设置了jcef的全局user agent，会影响其他使用了jcef并且依赖会user agent的插件

### ISSUE THREAD

**Issue by cnzhujie** [alibaba-cloud-toolkit/cosy#133]
**Describe the bug（描述您遇到的问题）**
我们公司内网有一个插件，会基于jcef打开sso登录页面进行登录，有用户反馈，安装了cosy插件之后，打开的sso页面变成了移动端的页面，导致无法进行登录。排查下来，是因为cosy插件修改了全局的cefSettings.user_agent导致的。

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/4935935/196396076-663d2bec-b515-4fe3-aee1-be9334f8fc97.png)

<img width="261" alt="image" src="https://user-images.githubusercontent.com/4935935/196396855-1de1247c-19d6-4ce0-a10d-5b7db0d17848.png">

**System（本地系统）**
 - OS: Mac
 - Cosy Version: 0.10.3.2

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
cnzhujie@qq.com

**Comment by zhangyukun230** [comment]
这个问题，我们先记录一下，后续会尽快看一下，去修复。

**Comment by liulhdarks** [comment]
试试新发布的0.10.4-beta版本，在设置中将搜索结果打开方式从“IDE内”修改为“打开浏览器”，然后重启IDE试试
