### ISSUE TITLE
新版本

### ISSUE THREAD

**Issue by cjs3030** [alibaba-cloud-toolkit/cosy#136]
大概几时发下一个版本

**Comment by pinkyo** [comment]
这个还有人维护吗？

**Comment by zxdxjtu** [comment]
久等了，Cosy正在开发多语言兼容版本，以及一系列优化和缺陷修复。但是由于人力投入限制，更新周期会比较长。

**Comment by KeepEnthusiasm** [comment]
IDE EAP版还不支持使用

**Comment by zxdxjtu** [comment]
@KeepEnthusiasm EAP兼容版本0.10.3.3-beta版本已发布

**Comment by zxdxjtu** [comment]
您好，0.10.3-beta版本已发布，兔年之际支持语言也变two了，支持了PyCharm端的Python语言补全，欢迎体验。
