### ISSUE TITLE
IDEA 2022.3 版本不支持

### ISSUE THREAD

**Issue by 876529270** [alibaba-cloud-toolkit/cosy#139]
**Describe the bug（描述您遇到的问题）**
IDEA 2022.3 版本不支持

**To Reproduce（复现步骤）**

**Screenshots（截图）**
![2OK1O~7O JZ26 SAZ}2HKVM](https://user-images.githubusercontent.com/26027308/204945527-e3b71112-987f-447a-9909-cb309ca415b8.png)

**System（本地系统）**
 - OS: window 10
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
你好，223版本对应的兼容版本0.10.3.3-beta已经在审批中，你可以通过
http://toolkit.aliyun.com/idea/cosy-intellij-beta-latest.zip
手动下载离线包并在本地安装

**Comment by zxdxjtu** [comment]
0.10.3.3-beta已发布
