### ISSUE TITLE
Android studio 代码没有提示，代码示例搜索提示未找到相关结果 

### ISSUE THREAD

**Issue by 30sunling** [alibaba-cloud-toolkit/cosy#14]

**Comment by HaoboGu** [comment]
你好，请先升级插件至最新版本。

如果升级至最新版本后问题仍未解决，你按照以下步骤来帮助我们排查问题：

1. 在IDE最上方的菜单栏中点击Help，选择Show Log in Explorer/Finder
2. 上传idea.log文件到本页面
3. 打开~/.cosy/logs，上传cosy.log和cosy-local.logxxx至本页面
谢谢！

**Comment by zxdxjtu** [comment]
没有进一步信息，issue先关闭，更新到最新版本，如有问题欢迎联系。如果是需要在无网络的机器上安装（虽然Cosy使用过程中不需要网络，但是安装时会去下载环境依赖），这种情况可以用纯本地版本：https://toolkit.aliyun.com/idea/cosy-intellij-beta-latest-all-in-one.zip
