### ISSUE TITLE
快捷键与Window11系统自带的截国工具冲突

### ISSUE THREAD

**Issue by JadeLuo** [alibaba-cloud-toolkit/cosy#140]
**Please describe the feature you request（请描述您的需求）**
解决与Window11快捷键冲突问题，目前未发现可修改系统自带的截图工具或通过修改cosy快捷键

**Describe the solution you'd like （请描述您的解法）**
增加可修改cosy默认的Win/Command+Shift+S快捷键功能
可修改cosy默认的Win/Command+Shift+S快捷键
**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
jadeluo@163.com

**Comment by liulhdarks** [comment]
快捷键是可以修改的，可以尝试在Preferences -> Keymap 中修改Cosy搜索的默认快捷键

![image](https://user-images.githubusercontent.com/7029328/205541733-2e61da4d-7a95-4113-82aa-3379f3a00693.png)
