### ISSUE TITLE
CPU 100% 占用

### ISSUE THREAD

**Issue by thefivestar** [alibaba-cloud-toolkit/cosy#146]
**Describe the bug（描述您遇到的问题）**
cpu占用100%

**To Reproduce（复现步骤）**
无，偶尔出现

**Screenshots（截图）**
暂无

**System（本地系统）**
 - OS:  Windows 10 22H2
 - Cosy Version: 0.10.4

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

日志全部是：
~~~
2023-01-12T09:46:17.292+0800	WARN	Error when deleting table:Txn is too big to fit into one request
~~~

**Comment by liulhdarks** [comment]
cosy.log和cosy-local.log日志麻烦提供一下

**Comment by thefivestar** [comment]
[cosy-2023-01-10T06-46-07.211.log](https://github.com/alibaba-cloud-toolkit/cosy/files/10398813/cosy-2023-01-10T06-46-07.211.log)
[cosy-local-2023-01-10.log](https://github.com/alibaba-cloud-toolkit/cosy/files/10398816/cosy-local-2023-01-10.log)

**Comment by liulhdarks** [comment]
请尝试删除一下~/.cosy/tmp/cache目录，然后杀掉cosy进程

**Comment by thefivestar** [comment]
发现了复现的步骤，maven打包后会触发
~~~
mvn clean package
~~~

**Comment by thefivestar** [comment]
最新的日志，只存在cosy.log，没有找到相应的cosy-local.log：
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/10400335/cosy.log)

**Comment by liulhdarks** [comment]
收到，这个问题我们本地没有复现，从日志来看是在做maven打包时，idea对所有文件执行了保存操作，导致cosy的模型在不断的对每个文件做更新，所以导致cpu升高，你可以检查下idea有没有相关配置，我们也会想办法避免这种情况，争取在下个版本修复，感谢反馈！

**Comment by thefivestar** [comment]
同环境下，最新的0.10.4-beta releases版本已修复该问题
