### ISSUE TITLE
请问新一年的开发计划有没有呢？希望早日支持 VSCODE ，支持更多语言（Python）

### ISSUE THREAD

**Issue by Jface001** [alibaba-cloud-toolkit/cosy#148]
**Please describe the feature you request（请描述您的需求）**
新一年希望支持更多 IDE，支持更多语言

**Comment by zxdxjtu** [comment]
谢谢支持，我们会努力的，兔年之际Cosy支持语言也变two了，最新的0.10.4-beta版本支持了PyCharm端的Python语言补全，欢迎体验，也祝您新春快乐，阖家幸福～

**Comment by Jface001** [comment]
@zxdxjtu VSCODE 很需要~  祝您新春愉快，假期愉快
