### ISSUE TITLE
IDEA 2021.3 版本不兼容该插件

### ISSUE THREAD

**Issue by jounzhang** [alibaba-cloud-toolkit/cosy#15]
IDEA 2021.3 版本不兼容该插件
incompatible:requires IDE build 212.* or earlier

**Comment by HaoboGu** [comment]
我们正在处理中，预计下周之前兼容哈

**Comment by zxdxjtu** [comment]
您好，新版本支持213版本，离线包已更新至https://github.com/alibaba-cloud-toolkit/cosy/releases/tag/0.9.5-beta，插件市场正在审核中，即将生效。
