### ISSUE TITLE
根据文档操作补好两个dll后提示 点击cosylocal 出现错误提示

### ISSUE THREAD

**Issue by Wang-2021-git** [alibaba-cloud-toolkit/cosy#150]
**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/83957783/217735401-7a06c1a2-70bf-4d75-91a6-ee5d734ad6ee.png)

**System（本地系统）**
 - OS: windows11
 - Cosy Version: 22h2

**Comment by liulhdarks** [comment]
这种情况表示dll不是64位的，需要下载64位的dll，你是安装的什么版本，差哪些dll

**Comment by Wang-2021-git** [comment]
> 这种情况表示dll不是64位的，需要下载64位的dll，你是安装的什么版本，差哪些dll

安装的0.2.13版本（idea插件库安装）
之前缺失的DLL为 libstdc++-6.dll 安装后提示 上述截图 跟 缺失libgcc_s_sjlj-1.dll 安装该dll后 只有这个提示了

**Comment by liulhdarks** [comment]
[缺失Windows DLL下载](http://toolkit.aliyun.com/idea/x86_64_windows_require_dll.zip)
你试试这个压缩包里面的dll

**Comment by Wang-2021-git** [comment]
> [缺失Windows DLL下载](http://toolkit.aliyun.com/idea/x86_64_windows_require_dll.zip) 你试试这个压缩包里面的dll

可以了
