### ISSUE TITLE
代码补全没有提示

### ISSUE THREAD

**Issue by Wang-2021-git** [alibaba-cloud-toolkit/cosy#151]
代码补全没有提示

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/83957783/217755661-afc2c2e0-b149-48b6-b51c-8cee801e1a2b.png)
![image](https://user-images.githubusercontent.com/83957783/217755755-751c48b2-4f8a-4111-8029-795a68eee685.png)

**System（本地系统）**
 - OS: win11
 - Cosy Version: 0.2.13
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/10694850/cosy.log)

目前删除了用户路径的.cosy目录 卡在idea加载数分钟了 不知道是否正常 任务管理器里有cosy进程

**Comment by liulhdarks** [comment]
把cosy进程杀掉再启动可以吗

**Comment by Wang-2021-git** [comment]
> 把cosy进程杀掉再启动可以吗

换成手机热点 进idea了 也有补全提示了 
然后发现了这个 不知道是我这问题还是什么原因
![image](https://user-images.githubusercontent.com/83957783/217759529-fb518c71-12e3-4613-9eda-b96bcb511122.png)

**Comment by liulhdarks** [comment]
这是那个部分的文字乱码了，麻烦截图截全一点呢

**Comment by Wang-2021-git** [comment]
> 这是哪个部分的文字乱码了，麻烦截图截全一点呢

![image](https://user-images.githubusercontent.com/83957783/217761999-4d763b2d-045b-4a71-8e41-7b63b6722c49.png)

**Comment by liulhdarks** [comment]
好的，问题收到，应该跟系统字体有关系，下个版本尝试修复一下

**Comment by wh414760981** [comment]
@liulhdarks 
原因：
  .cosy\model 目录中存在 `0.0.3` 和 `0.1.0` 这两个目录， 应该是多次卸载安装导致多了一个 `0.1.0` 。
![image](https://user-images.githubusercontent.com/8133783/217988672-2c60f430-f77b-4b37-b1e3-33ec31ae043e.png)
处理方法：
  卸载插件，删除 .cosy 目录中的所有文件。然后重现安装插件。

**Comment by zxdxjtu** [comment]
感谢反馈，issue关了哈
