### ISSUE TITLE
占用大量内存，不释放

### ISSUE THREAD

**Issue by 2687792886** [alibaba-cloud-toolkit/cosy#154]
**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/30792524/218934235-aec86e40-a8f8-4742-9174-202464bf3310.png)
![image](https://user-images.githubusercontent.com/30792524/218934306-040bb1d6-3c8b-4d5b-b877-19fa081b3c46.png)
![image](https://user-images.githubusercontent.com/30792524/218934387-e8509561-bed5-4bbd-b722-93b6550e1ecb.png)

**System（本地系统）**
 - OS: win10
 - Cosy Version: 0.10.4-beta

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
2687792886@qq.com

**Comment by 2687792886** [comment]
日志
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/10739397/cosy.log)
[cosy-2023-02-15T03-43-44.777.log](https://github.com/alibaba-cloud-toolkit/cosy/files/10739399/cosy-2023-02-15T03-43-44.777.log)
[cosy-2023-02-15T03-43-45.382.log](https://github.com/alibaba-cloud-toolkit/cosy/files/10739400/cosy-2023-02-15T03-43-45.382.log)
[cosy-2023-02-15T03-43-45.917.log](https://github.com/alibaba-cloud-toolkit/cosy/files/10739415/cosy-2023-02-15T03-43-45.917.log)
[cosy-2023-02-15T03-43-47.214.log](https://github.com/alibaba-cloud-toolkit/cosy/files/10739420/cosy-2023-02-15T03-43-47.214.log)

**Comment by liulhdarks** [comment]
这个问题已经在开发版修复，你可以先试试把.cosy目录下的tmp目录，杀掉cosy进程试试

**Comment by liulhdarks** [comment]
0.10.5-beta版本已经发布，修复内存占用过高的问题，请到插件市场或Cosy官网更新
