### ISSUE TITLE
一直在“正在更新阿里云智能编码助手Cosy”

### ISSUE THREAD

**Issue by Nagi30001** [alibaba-cloud-toolkit/cosy#157]
![](https://nagi-study-data-1259685012.cos.ap-chengdu.myqcloud.com/picgo/1676537425105.png)

**Comment by liulhdarks** [comment]
麻烦发一下日志文件 Mac用户：~/.cosy/logs，Windows用户：C盘/用户/[用户名]/.cosy/logs）

**Comment by Nagi30001** [comment]
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/10754138/cosy.log)
15、16号没有生成对应的日志文件

**Comment by Royalreairman** [comment]
我这边的日志写的是更新失败

![1676737954512](https://user-images.githubusercontent.com/96969397/219877173-205d7202-0c66-41a1-bb78-878be612b38c.png)

**Comment by Nagi30001** [comment]
不太清楚怎么回事，代码提示也没有了

**Comment by qiange167** [comment]
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/10779001/cosy.log)
我的也是

**Comment by liulhdarks** [comment]
> 

麻烦先杀掉cosy进程，然后删除一下.cosy目录，重启IDE试试

**Comment by liulhdarks** [comment]
> [cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/10754138/cosy.log) 15、16号没有生成对应的日志文件

麻烦先杀掉cosy进程，然后删除一下.cosy目录，重启IDE试试

**Comment by liulhdarks** [comment]
> 我这边的日志写的是更新失败
> 
> ![1676737954512](https://user-images.githubusercontent.com/96969397/219877173-205d7202-0c66-41a1-bb78-878be612b38c.png)

@Royalreairman 你之前有安装过吗，还是第一次使用，如果是第一次使用，可能是网络有点问题，可以删除.cosy目录试试，如果还是不行，可以安装all-in-one版本

**Comment by liulhdarks** [comment]
> [cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/10779001/cosy.log) 我的也是

@qiange167 麻烦先杀掉cosy进程，然后删除一下.cosy目录，重启IDE试试

**Comment by Royalreairman** [comment]
把.cosy删了可以，在用户那个文件下面， 如果电脑安装了其他ai工具可能出现代码提示不行的情况
