### ISSUE TITLE
安装插件之后 idea有明显卡顿不流畅现象,内存占用也不高 望排查

### ISSUE THREAD

**Issue by wuyaLord** [alibaba-cloud-toolkit/cosy#158]
**Describe the bug（描述您遇到的问题）**

**To Reproduce（复现步骤）**

**Screenshots（截图）**

**System（本地系统）**
 - OS: 
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by liulhdarks** [comment]
麻烦发一下日志文件 Mac用户：~/.cosy/logs，Windows用户：C盘/用户/[用户名]/.cosy/logs）

**Comment by wuyaLord** [comment]
> 麻烦发一下日志文件 Mac用户：~/.cosy/logs，Windows用户：C盘/用户/[用户名]/.cosy/logs）
[Uploading cosy.log…]()
