### ISSUE TITLE
IDEA开久后发现Cosy内存占用很高

### ISSUE THREAD

**Issue by qq295190549** [alibaba-cloud-toolkit/cosy#159]
**Describe the bug（描述您遇到的问题）**
IDEA开久后发现Cosy内存占用很高

**To Reproduce（复现步骤）**
IDEA开几天不关闭

**Screenshots（截图）**
<img width="939" alt="image" src="https://user-images.githubusercontent.com/17867113/222091394-7209deb8-5ffe-450a-b718-6a0ab6d75f49.png">

**System（本地系统）**
 - OS: MacOS 11.2.3
 - Cosy Version: 0.10.4-beta

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
295190549@qq.com

**Comment by qq295190549** [comment]
今天内存占用升到了18G

**Comment by liulhdarks** [comment]
麻烦发一下日志文件（Mac用户：~/.cosy/logs，Windows用户：C盘/用户/[用户名]/.cosy/logs）

**Comment by qq295190549** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by liulhdarks** [comment]
你可以尝试先杀掉Cosy进程，然后删除~/.cosy/tmp，再重启IDE试试

**Comment by liulhdarks** [comment]
0.10.5-beta版本已经发布，修复内存占用过高的问题，请到插件市场或Cosy官网更新

**Comment by qq295190549** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
