### ISSUE TITLE
当前版本在idea 2021.3不被支持

### ISSUE THREAD

**Issue by adairSong** [alibaba-cloud-toolkit/cosy#16]
在idea 2021.3 的plugins marketplace找不到插件，从离线安装提示当前版本不被支持。
![20211203104529](https://user-images.githubusercontent.com/11285368/144536246-b6c60d15-6ae3-45ce-9e93-94db438cb171.png)

**Comment by HaoboGu** [comment]
你好，新版本在这里下载：https://github.com/alibaba-cloud-toolkit/cosy/releases/tag/0.9.5-beta
