### ISSUE TITLE
可以连接到主机 但是无法进行热部署文件

### ISSUE THREAD

**Issue by wuyaLord** [alibaba-cloud-toolkit/cosy#161]
![image](https://user-images.githubusercontent.com/77916470/223909520-ea46f250-31bf-4fca-93e7-96554deba986.png)

![image](https://user-images.githubusercontent.com/77916470/223909493-5160e558-56f1-453b-9cb4-995e0c5fe011.png)

**Comment by wuyaLord** [comment]
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/10927400/cosy.log)
日志文件

**Comment by wuyaLord** [comment]
idea版本 2.22.3.3

**Comment by zxdxjtu** [comment]
您好，这个不是cosy插件的功能。应该是cloud toolkit的热部署吧，请移步https://github.com/alibaba-cloud-toolkit/cloud-toolkit-jetbrains/issues，或者去钉群答疑
