### ISSUE TITLE
代码提示插件不兼容最新的IDEA 2023.1 EAP

### ISSUE THREAD

**Issue by fwnan** [alibaba-cloud-toolkit/cosy#163]
**Please describe the feature you request（请描述您的需求）**

**Describe the solution you'd like （请描述您的解法）**

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
请发送下About IntelliJ的内容，看下具体的版本号。
另外请确认下Cosy的版本号是不是0.10.4-beta最新版，最新版是兼容231版本的

**Comment by fwnan** [comment]
@zxdxjtu  开发者你好,  以下是报错信息: 
Plugin 'Alibaba Cloud AI Coding Assistant' (version '0.10.4-beta') is not compatible with the current version of the IDE, because it requires build 223.* or older but the current build is IU-231.8109.2

**Comment by fwnan** [comment]
<img width="599" alt="11123214532" src="https://user-images.githubusercontent.com/71653989/225378810-67ccd0bf-7887-4af5-bcd4-3104971f02b2.png">

**Comment by zxdxjtu** [comment]
抱歉，看错版本号了，231确实还没有兼容，我们尽快检查下兼容性，做下小版本发布，在此之前可能只能在223以前的版本中使用Cosy

**Comment by fwnan** [comment]
感谢回复, 期待尽快发布新版本.

**Comment by biduolin** [comment]
cosy有内测钉钉群吗 wiki的链接已失效 问阿里云的人也不知道

**Comment by zxdxjtu** [comment]
@biduolin 邀请你加入钉钉群聊阿里云智能编码插件内测用户群，点击进入查看详情 https://qr.dingtalk.com/action/joingroup?code=v1,k1,MC+5H9641iNrvSHxruRl4QrrYdIlwfxRMxGW1e+IOew=&_dt_no_comment=1&origin=11

**Comment by changshunxu520** [comment]
2023.1已经发布，什么时候能适配插件？

**Comment by liulhdarks** [comment]
0.10.5-beta版本已经发布，适配2023.1版本，请到插件市场或Cosy官网更新
