### ISSUE TITLE
cosy 后台任务一直出现正在更新

### ISSUE THREAD

**Issue by yuyuyu202319** [alibaba-cloud-toolkit/cosy#165]
**Describe the bug（描述您遇到的问题）**
cosy 后台任务一直出现正在更新

**To Reproduce（复现步骤）**
写代码时，后台更新线程一直增加，达到过40左右。停止写代码的时候，慢慢就结束了

**Screenshots（截图）**

![image](https://user-images.githubusercontent.com/126887107/226265600-2ef65f10-832a-4826-9b91-cfc4d0f7d121.png)

**System（本地系统）**
 - OS: window11 ， IntelliJ IDEA 2022.3.2 (Ultimate Edition)
 - Cosy Version: 0.10.4-beta

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by yuyuyu202319** [comment]
![image](https://user-images.githubusercontent.com/126887107/226267462-d5e59461-7d58-4f93-bdf6-fb000612242e.png)

**Comment by yuyuyu202319** [comment]
![image](https://user-images.githubusercontent.com/126887107/226267932-dfeac033-c6c6-4748-8a5a-06ace1ec4332.png)

**Comment by zxdxjtu** [comment]
麻烦提供下cosy的日志：
目录： ~/.cosy/logs
并且提供下cosy的版本信息

最好能提供下idea的日志。
idea工具栏 Help > Find log in Finder > idea.log

**Comment by yuyuyu202319** [comment]
[cosy-local.log.2023-03-20.log](https://github.com/alibaba-cloud-toolkit/cosy/files/11035353/cosy-local.log.2023-03-20.log)

[idea-log.zip](https://github.com/alibaba-cloud-toolkit/cosy/files/11035367/idea-log.zip)

Cosy Version: 0.10.4-beta

**Comment by zxdxjtu** [comment]
请问除了cosy-local.log。有cosy.log吗

**Comment by zxdxjtu** [comment]
请尝试杀掉cosy进程，然后删除.cosy目录，重启idea

**Comment by yuyuyu202319** [comment]
> 请尝试杀掉cosy进程，然后删除.cosy目录，重启idea
好的。我试一试

**Comment by yuyuyu202319** [comment]
> 请尝试杀掉cosy进程，然后删除.cosy目录，重启idea

通过这个方式解决了。
