### ISSUE TITLE
搜索之后，不显示代码示例

### ISSUE THREAD

**Issue by yuyongkratos** [alibaba-cloud-toolkit/cosy#166]
**Describe the bug（描述您遇到的问题）**
在输入框内输入API名称，无法搜索出代码示例

**To Reproduce（复现步骤）**
点击ExecutorService
提示更新cosy
搜索不出结果
另：删除.cosy文件夹后，重启idea后还是不好使。

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/19532530/227456092-5c9e07ca-a1b3-4fc5-8598-238d8e33f746.png)
![image](https://user-images.githubusercontent.com/19532530/227456110-08af36ed-2e0f-438a-b9e3-34ef0dc1e5ba.png)

**System（本地系统）**
 - OS: Win10
 - Cosy Version: 0.10.4-beta

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
yuyonghaerbin@163.com

附件如下：
idea.log
[idea.log](https://github.com/alibaba-cloud-toolkit/cosy/files/11059598/idea.log)
cosy.log
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/11059600/cosy.log)

**Comment by liulhdarks** [comment]
看日志是下载依赖组件失败，可以尝试使用all-in-one版本，安装前最好先删除.cosy目录，https://toolkit.aliyun.com/idea/cosy-intellij-beta-latest-all-in-one.zip

**Comment by yuyongkratos** [comment]
> 看日志是下载依赖组件失败，可以尝试使用all-in-one版本，安装前最好先删除.cosy目录，https://toolkit.aliyun.com/idea/cosy-intellij-beta-latest-all-in-one.zip

all-in-one可以正常使用。
