### ISSUE TITLE
增加代码补全功能启用开关

### ISSUE THREAD

**Issue by aiLvXuan** [alibaba-cloud-toolkit/cosy#169]
**Please describe the feature you request（请描述您的需求）**
希望可以设置是否启用代码补全。
1. 小公司电脑配置真的低，内存不够用（人微言轻，申请不了配置）
2. 习惯IDEA的自动提示，熟悉快捷输入，会被插件打断思路
3. 目前插件没法让IDEA自动导包
4. 输入一个变量名、方法名字时，无法只输入其中几个字母直接弹窗完整的变量名；
5. 目前是在AndroidStudio 使用Kotlin语言，所以不怎么需要插件的自动补全
6. 为什么我还要安装插件？**文档搜索实在是太好用了**

**Describe the solution you'd like （请描述您的解法）**

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by liulhdarks** [comment]
收到，下个版本支持

**Comment by liulhdarks** [comment]
0.10.5-beta版本已经发布，增加代码补全开关，请到插件市场或Cosy官网更新
