### ISSUE TITLE
跟idea版本不兼容

### ISSUE THREAD

**Issue by WorkJun** [alibaba-cloud-toolkit/cosy#172]
**Describe the bug（描述您遇到的问题）**

Plugin 'Alibaba Cloud AI Coding Assistant' (version '0.10.4-beta') is not compatible with the current version of the IDE, because it requires build 223.* or older but the current build is IU-231.8109.175 Plugin 'Alibaba Cloud Toolkit' (version '2023.2.1-223') is not compatible with the current version of the IDE, because it requires build 223.* or older but the current build is IU-231.8109.175

**Comment by liulhdarks** [comment]
231.8109.175版本正在适配中，稍后会发布

**Comment by changshunxu520** [comment]
> 231.8109.175版本正在适配中，稍后会发布

更新啊，更新啊
