### ISSUE TITLE
代码补全和搜索都不可用

### ISSUE THREAD

**Issue by jinzisen** [alibaba-cloud-toolkit/cosy#173]
**Describe the bug（描述您遇到的问题）**
代码补全和搜索都不可用

**To Reproduce（复现步骤）**

**Screenshots（截图）**

**System（本地系统）**
 - OS: windows
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
1049536678@qq.com

**Comment by liulhdarks** [comment]
看上去是下载模型失败了，可以试试all-in-one版本，https://toolkit.aliyun.com/idea/cosy-intellij-beta-latest-all-in-one.zip

**Comment by jinzisen** [comment]
好的 我试试
