### ISSUE TITLE
idea插件描述有误

### ISSUE THREAD

**Issue by yanggi** [alibaba-cloud-toolkit/cosy#176]
**Describe the bug（描述您遇到的问题）**
idea plugin marketplace插件英文描述单词错误，【immsersed】应为【immersed】

**To Reproduce（复现步骤）**

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/14255177/231335182-72c85b24-a357-4e51-ab43-3369cf262193.png)

**System（本地系统）**
 - OS: 
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
以及修复，会随着下个版本发布，感谢
