### ISSUE TITLE
Mac安装最新版本cosy插件无法搜索

### ISSUE THREAD

**Issue by deyunvip** [alibaba-cloud-toolkit/cosy#177]
**Describe the bug（描述您遇到的问题）**
成功在Macbook pro笔记本的IDEA上安装最新版本0.10.5-beta插件后，无法搜索任何关键字

**To Reproduce（复现步骤）**

**Screenshots（截图）**
![Uploading image.png…]()

**System（本地系统）**
 - OS: mac os13.1 (22C65)
 - Cosy Version: 0.10.5-beta

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
deyunwang@126.com

**Comment by liulhdarks** [comment]
cc #178
