### ISSUE TITLE
使用期间有ide无响应只能强退和电脑自动重启的问题

### ISSUE THREAD

**Issue by princeHe** [alibaba-cloud-toolkit/cosy#18]
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/7658305/cosy.log)

**Comment by HaoboGu** [comment]
请问一下，插件端版本是0.9.5-beta吗？

**Comment by zxdxjtu** [comment]
方便提供下IDEA的log吗，IDEA内点击Help->Show Log in Finder，希望能看到无响应时段对应的ThreadDump日志，无法区分的话，能否把整个log日志压缩提供给我们排查，感谢
![image](https://user-images.githubusercontent.com/9382205/144949964-f4b32336-5f69-4ff5-9ec4-47f9ab9eb344.png)

**Comment by princeHe** [comment]
[threadDumps-freeze-20211203-172805-AI-203.7717.56.2031.7678000.zip](https://github.com/alibaba-cloud-toolkit/cosy/files/7665852/threadDumps-freeze-20211203-172805-AI-203.7717.56.2031.7678000.zip)

**Comment by zxdxjtu** [comment]
感谢反馈，代码行已经定位，不过暂时没能复现，请问您后来有再次出现过无响应的情况吗？我们会优化下相关代码，再下个版本(大概下周)发布。

**Comment by zxdxjtu** [comment]
该问题已在0.9.6-beta版本修复，欢迎升级体验✅
