### ISSUE TITLE
all-in-one离线包版本还是在2022.3，请更新到2023.1

### ISSUE THREAD

**Issue by Jay-xiansen** [alibaba-cloud-toolkit/cosy#182]
**Please describe the feature you request（请描述您的需求）**

**Describe the solution you'd like （请描述您的解法）**

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
我们会尽快适配

**Comment by zxdxjtu** [comment]
您好，all-in-one版本已适配完成：https://toolkit.aliyun.com/idea/cosy-intellij-beta-latest-all-in-one.zip
