### ISSUE TITLE
只有代码补全，没有搜索的侧边栏

### ISSUE THREAD

**Issue by 371606879** [alibaba-cloud-toolkit/cosy#183]
**Describe the bug（描述您遇到的问题）**

只有代码补全，没有搜索的侧边栏
**To Reproduce（复现步骤）**

**Screenshots（截图）**

**System（本地系统）**
 - OS: 
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by 371606879** [comment]
view 里面的 Tool Windows也没有？是因为pycharm版本的问题吗？

**Comment by zxdxjtu** [comment]
抱歉，目前代码搜索暂时只支持Java语言，因此没有在PyCharm里面透出。

**Comment by 371606879** [comment]
喔喔 这样啊

**Comment by zxdxjtu** [comment]
后续会逐步开发，目前由于代码片段只处理了Java的数据，文档也多为Java相关，Python的搜索需要进一步排期开发
