### ISSUE TITLE
离线包在idea启动后报错libwinpthread-1.dll被另一个程序使用，能正常使用离线包

### ISSUE THREAD

**Issue by danteair** [alibaba-cloud-toolkit/cosy#189]
**Describe the bug（描述您遇到的问题）**
idea启动后会弹出n次报错，不影响cosy正常使用。每次报错日志基本相同，除了后台下载的zip文件名不同

**To Reproduce（复现步骤）**
启动idea

**Screenshots（截图）**
![image](https://github.com/alibaba-cloud-toolkit/cosy/assets/57834436/1e04b031-1656-45be-8864-bc98f457289b)
![image](https://github.com/alibaba-cloud-toolkit/cosy/assets/57834436/053d499e-bb2c-4f11-87a5-e089e119733b)
![image](https://github.com/alibaba-cloud-toolkit/cosy/assets/57834436/c52b51ca-cdb3-4f5c-af8b-01a1cefb3668)
![image](https://github.com/alibaba-cloud-toolkit/cosy/assets/57834436/4b2915ac-50a5-4a11-9aa0-268931b05637)

**System（本地系统）**
 - OS: win11
 - Cosy Version: 0.10.5-beta-all-in-local
 - Idea: 2023.1.2(Ultimate Edition)
**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by liulhdarks** [comment]
先Kill掉Cosy和cosylocal进程，再手动把.cosy目录删除再试试
