### ISSUE TITLE
代码示例搜索可以搜索注解

### ISSUE THREAD

**Issue by actionqq** [alibaba-cloud-toolkit/cosy#19]
希望代码示例搜索可以搜索@注解
![image](https://user-images.githubusercontent.com/10918479/145325962-ccfecf55-b974-4e37-8aa2-e444bd850751.png)

**Comment by zxdxjtu** [comment]
收到需求，我们会做排期，不过可能需要些时间，预计要到年后，issue先关闭啦，感谢反馈。

**Comment by meiMingle** [comment]
半年？阿尤歇若斯？

**Comment by meiMingle** [comment]
> 收到需求，我们会做排期，不过可能需要些时间，预计要到年后，issue先关闭啦，感谢反馈。

半年？阿尤歇若斯？
