### ISSUE TITLE
无法使用代码智能提示

### ISSUE THREAD

**Issue by xiaoba66X** [alibaba-cloud-toolkit/cosy#190]
搜索正常使用，代码提示无法使用，还是IDEA自带的提示

**System（本地系统）**
 - OS: Windows10 64
 - Cosy Version: 0.2.14

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
20488020@qq.com

[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/11882581/cosy.log)

**Comment by zxdxjtu** [comment]
麻烦提供下~/.cosy/log日志
或者试试下载最新版本cosy 0.10.6-beta版本，杀死cosy进程，删除.cosy目录，重启IDEA
