### ISSUE TITLE
安装后C盘被塞几个G

### ISSUE THREAD

**Issue by tufeng1992** [alibaba-cloud-toolkit/cosy#191]
可以支持定制化离线文件目录么？

公司电脑本来磁盘就比较小，默认放在C盘的zip文件占用空间太多了希望可以调整配置

**Comment by liulhdarks** [comment]
需求收到。会多几个GB？有截图吗

**Comment by tufeng1992** [comment]
![image](https://github.com/alibaba-cloud-toolkit/cosy/assets/12758480/2f857a61-2265-4851-83a1-abb626573c96)
安装cosy后，会在C盘用户目录下\AppData\Local\Temp安装很多cosy_xxx的压缩文件，文件比较大。希望可以配置化安装目录

**Comment by liulhdarks** [comment]
这些临时文件是可以删掉的，后面我们会自动删一下

**Comment by tufeng1992** [comment]
删除后再idea里面在使用cosy会报错的，所以我是又重新安装回来了
