### ISSUE TITLE
Not compatible with the version of your running IDE (IntelliJ IDEA 2023.2)

### ISSUE THREAD

**Issue by barry8023** [alibaba-cloud-toolkit/cosy#197]
下载的最新版ide2023.2不支持cosy，我希望能够使用
安装时提示Not compatible with the version of your running IDE (IntelliJ IDEA 2023.2)

zhanglin@zepp.com

**Comment by liulhdarks** [comment]
好的，目前新版本兼容性还存在一些问题，我们会尽快解决。

**Comment by liulhdarks** [comment]
http://toolkit.aliyun.com/idea/cosy-intellij-0.10.6-beta.zip  
可以试一下新版本，后面会上架到插件市场
