### ISSUE TITLE
第二次输入框会被挡住

### ISSUE THREAD

**Issue by Eleven-M** [alibaba-cloud-toolkit/cosy#198]
**Describe the bug（描述您遇到的问题）**

**To Reproduce（复现步骤）**
输入一次搜索，第二次重新输入，选择器被遮挡

**Screenshots（截图）**

![image](https://github.com/alibaba-cloud-toolkit/cosy/assets/12506132/22a0910f-a7dc-4d89-b114-0940909e6420)

**System（本地系统）**
 - OS: 
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by liulhdarks** [comment]
![image](https://github.com/alibaba-cloud-toolkit/cosy/assets/7029328/eef4df92-c13b-4cd7-bf55-be3ffc5eaaa6)
要不先试试其他输入法？
