### ISSUE TITLE
重新安装了几次，也没有看到你们示例里面的提示信息出来

### ISSUE THREAD

**Issue by ruancong** [alibaba-cloud-toolkit/cosy#2]
重新安装了几次，也没有看到你们示例里面的提示信息出来。右边也有“代码示例搜索”的导航菜单出现。
没有提示功能，有搜索功能
![image](https://user-images.githubusercontent.com/7631338/139184040-235e9467-f303-4a23-8e8d-f263ed75fa92.png)
![image](https://user-images.githubusercontent.com/7631338/139184304-df27dbd0-cc73-4eab-b849-23d169a6b96f.png)
![image](https://user-images.githubusercontent.com/7631338/139184327-3644bb75-8f68-4d14-bd30-941a96350ea8.png)
日志文件
[idea.log](https://github.com/alibaba-cloud-toolkit/cosy/files/7430979/idea.log)

**Comment by HaoboGu** [comment]
已修复，请更新至0.9.2-beta版本
