### ISSUE TITLE
代码自动补全联想的时候期望更加智能

### ISSUE THREAD

**Issue by LambdaV5** [alibaba-cloud-toolkit/cosy#20]
![image](https://user-images.githubusercontent.com/17512402/145356452-7928f16f-7919-4fce-af4a-9283d2f4486a.png)
如图所示，自动联想的时候希望能达到idea的水平

**Comment by HaoboGu** [comment]
你好，你的意是智能补全支持大小写模糊匹配对吧？这个我记录一下，会尽快支持

**Comment by LambdaV5** [comment]
是的，感谢！

**Comment by zxdxjtu** [comment]
**0.10.1-beta**版本正式上线啦，并且针对反馈较多的大小写问题，增加了大小写模糊匹配的功能。另外这个版本增加了StackOverflow问答搜索，可以在插件内部通过API或中英文自然语言描述搜索问答，欢迎体验。
