### ISSUE TITLE
在插件管理里面第二个动图显示异常

### ISSUE THREAD

**Issue by meiMingle** [alibaba-cloud-toolkit/cosy#21]
环境：Win10;idea2021.3;Alibaba Cloud AI Coding Assistant0.9.5-beta
![image](https://user-images.githubusercontent.com/39942874/146106447-8bcabb27-50a8-4a69-acec-d9739d0f67c5.png)

**Comment by zxdxjtu** [comment]
请问异常是指雪花片吗？这个是因IDEA的自动压缩图片导致的，目前无法完全规避，我们观察到其他某些插件的GIF动图有雪花片。详细的动图，可以直接从产品说明底部的Plugin homepage进入官网查看，也可以在github wiki （https://github.com/alibaba-cloud-toolkit/cosy/wiki/%E3%80%90%E4%BB%A3%E7%A0%81%E6%99%BA%E8%83%BD%E8%A1%A5%E5%85%A8%E3%80%91%E5%B8%AE%E5%8A%A9%E6%96%87%E6%A1%A3）中查阅，如果对我们的文档说明有不清楚或者不满意的地方，欢迎给我们提意见。
![image](https://user-images.githubusercontent.com/9382205/146116678-c500d5d4-5f1a-4abf-8979-bfd09cccfafc.png)

**Comment by meiMingle** [comment]
> 请问异常是指雪花片吗？这个是因IDEA的自动压缩图片导致的，目前无法完全规避，我们观察到其他某些插件的GIF动图有雪花片。详细的动图，可以直接从产品说明底部的Plugin homepage进入官网查看，也可以在github wiki （[https://github.com/alibaba-cloud-toolkit/cosy/wiki/%E3%80%90%E4%BB%A3%E7%A0%81%E6%99%BA%E8%83%BD%E8%A1%A5%E5%85%A8%E3%80%91%E5%B8%AE%E5%8A%A9%E6%96%87%E6%A1%A3）中查阅，如果对我们的文档说明有不清楚或者不满意的地方，欢迎给我们提意见。](https://github.com/alibaba-cloud-toolkit/cosy/wiki/%E3%80%90%E4%BB%A3%E7%A0%81%E6%99%BA%E8%83%BD%E8%A1%A5%E5%85%A8%E3%80%91%E5%B8%AE%E5%8A%A9%E6%96%87%E6%A1%A3%EF%BC%89%E4%B8%AD%E6%9F%A5%E9%98%85%EF%BC%8C%E5%A6%82%E6%9E%9C%E5%AF%B9%E6%88%91%E4%BB%AC%E7%9A%84%E6%96%87%E6%A1%A3%E8%AF%B4%E6%98%8E%E6%9C%89%E4%B8%8D%E6%B8%85%E6%A5%9A%E6%88%96%E8%80%85%E4%B8%8D%E6%BB%A1%E6%84%8F%E7%9A%84%E5%9C%B0%E6%96%B9%EF%BC%8C%E6%AC%A2%E8%BF%8E%E7%BB%99%E6%88%91%E4%BB%AC%E6%8F%90%E6%84%8F%E8%A7%81%E3%80%82) ![image](https://user-images.githubusercontent.com/9382205/146116678-c500d5d4-5f1a-4abf-8979-bfd09cccfafc.png)

嗯是的，就是雪花片

**Comment by meiMingle** [comment]
或许我应该把这个问题提交给idea社区

**Comment by meiMingle** [comment]
已提交给idea社区，等待修复 https://youtrack.jetbrains.com/issue/IDEA-284934
