### ISSUE TITLE
Wiki里面说可以离线使用，然而实际测试离线状态并没有智能补全

### ISSUE THREAD

**Issue by meiMingle** [alibaba-cloud-toolkit/cosy#22]
环境：Win10;idea2021.3;Alibaba Cloud AI Coding Assistant0.9.5-beta
![image](https://user-images.githubusercontent.com/39942874/146107450-b53ad609-a81a-42b6-9973-60d9b1a89641.png)
![image](https://user-images.githubusercontent.com/39942874/146107891-3c3a4369-1f72-4ca8-ab39-c7797c8cd44b.png)
![image](https://user-images.githubusercontent.com/39942874/146108072-d2b383e8-88d1-4d19-b577-0cd7c11168e7.png)

**Comment by zxdxjtu** [comment]
Cosy需要联网更新下载模型，之后便可以在离线模式下运行（后期会将模型打包，全程不用联网）。请问您是联网补出来以后，再断网补不出来吗？还是全程都没有联网？
能方便提供下用户根目录下的.cosy/logs/cosy.log供我们排查吗，非常感谢

**Comment by meiMingle** [comment]
> Cosy需要联网更新下载模型，之后便可以在离线模式下运行（后期会将模型打包，全程不用联网）。请问您是联网补出来以后，再断网补不出来吗？还是全程都没有联网？ 能方便提供下用户根目录下的.cosy/logs/cosy.log供我们排查吗，非常感谢

是全程没有联网，因为是在虚拟左面里开发没有联网

**Comment by meiMingle** [comment]
这个联网下载模型难道不是通过http协议下载的吗？我在idea中设置好了可以联网的http代理后，好像依然不好使
![image](https://user-images.githubusercontent.com/39942874/146125606-51fb9277-be01-4bd6-abf9-b944506e4ccf.png)

**Comment by HaoboGu** [comment]
我们的模型是托管在阿里云OSS上面，理论上是通过http下载的。因为我们还没有测试过虚拟桌面的情况，这里不太确定具体原因是什么，请问在虚拟桌面上可以打开：https://cn-hangzhou.oss.aliyun-inc.com/ 这个url吗？

**Comment by meiMingle** [comment]
我虚拟桌面无法直接联网，配置完http代理后在浏览器里可以访问 https://cn-hangzhou.oss.aliyun-inc.com/ ，但是返回状态码403
![image](https://user-images.githubusercontent.com/39942874/146138410-5906d833-6e97-4c72-9782-5e08602eee30.png)

**Comment by meiMingle** [comment]
> 我们的模型是托管在阿里云OSS上面，理论上是通过http下载的。因为我们还没有测试过虚拟桌面的情况，这里不太确定具体原因是什么，请问在虚拟桌面上可以打开：https://cn-hangzhou.oss.aliyun-inc.com/ 这个url吗？

我有一个猜测，这个下载模型的请求并非由java程序发起，而是由插件内包含的二进制程序XX.exe所发起的。如果是这样的话，建议将下载模型的请求改为通过由idea内的http组件发起。最终达到的目的就是，通过idea配置好http代理就能正常下载模型。

**Comment by HaoboGu** [comment]
> 我有一个猜测，这个下载模型的请求并非由java程序发起，而是由插件内包含的二进制程序XX.exe所发起的。如果是这样的话，建议将下载模型的请求改为通过由idea内的http组件发起。最终达到的目的就是，通过idea配置好http代理就能正常下载模型。

你说的是对的，问题我们记下来了，后面会尽快修复。感谢反馈！

**Comment by zxdxjtu** [comment]
纯本地all-in-one版本已发布，此issue关闭啦：https://toolkit.aliyun.com/idea/cosy-intellij-beta-latest-all-in-one.zip
