### ISSUE TITLE
不知为啥插件报了这个NullPointException

### ISSUE THREAD

**Issue by meiMingle** [alibaba-cloud-toolkit/cosy#23]
环境：Win10;idea2021.3;Alibaba Cloud AI Coding Assistant0.9.5-beta
![image](https://user-images.githubusercontent.com/39942874/146111548-ccc6a03f-1c3a-4a51-bb49-fd6af046f06a.png)

**Comment by zxdxjtu** [comment]
该问题已在0.9.6-beta版本修复，欢迎升级体验✅
