### ISSUE TITLE
建议把这个地方的跳转链接改为https://github.com/alibaba-cloud-toolkit/cosy/issues

### ISSUE THREAD

**Issue by meiMingle** [alibaba-cloud-toolkit/cosy#24]
环境：Win10;idea2021.3;Alibaba Cloud AI Coding Assistant0.9.5-beta
这个地方跳转的本意应该是跳转到能够反馈此插件问题的地方（report problem），现在给跳到了http://www.alibabacloud.com/ 那里也没有反馈此插件问题的入口哇！就算我在网站上联系到的阿里的客服小姐姐，就算客服小姐姐知道这个插件是干嘛地，大概率也会让我转到这里反馈吧！南辕北辙？
![image](https://user-images.githubusercontent.com/39942874/146112383-f8951cfc-26d9-4eb2-9187-b717931c7ac6.png)

**Comment by zxdxjtu** [comment]
感谢反馈，这个问题收到，已安排修复，预计会在12月底发布。
我研究一下如何修改您提到的链接。
关于错误上报，我们也正在研究如何提供一种更友好，更及时，更详细的机制，敬请期待。
如果您有钉钉的话，可以扫描我们的内测用户群，最近会有自然语言搜索的新功能供内测体验。
![image](https://user-images.githubusercontent.com/9382205/146115853-905096e0-34a7-41a8-87bc-ec533d5ca0c3.png)

**Comment by zxdxjtu** [comment]
该问题已在0.9.6-beta版本修复，欢迎升级体验✅

**Comment by meiMingle** [comment]
吐槽吐槽吐槽！！！不跳issue页面就算了，你跳https://developer.aliyun.com/tool/cosy?channel=idea_vendor 这里也行，页面上加个"问题反馈"的按钮跳issue页面或者加个钉钉群的二维码呀！它不香吗？
![image](https://user-images.githubusercontent.com/39942874/148188205-2a5872e6-c2d0-4058-a0ce-3e32bb00badb.png)
