### ISSUE TITLE
代码输入没有提示，代码示例搜索也没有内容显示

### ISSUE THREAD

**Issue by anyuan95** [alibaba-cloud-toolkit/cosy#27]
日志文件：
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/7795290/cosy.log)

系统版本：macOS Monterey 12.1 （Intel）
idea版本：IntelliJ IDEA 2021.3 (Ultimate Edition)
插件版本：0.9.6-beta

**Comment by HaoboGu** [comment]
重启IDE再尝试一下呢？ 看起来可能是本地环境没有初始化成功

**Comment by anyuan95** [comment]
我重新开了一个idea项目，启动的时候卡住了好久，现在可以给出提示和示例搜索了...
不过我安装插件后也马上进行重启了，那次重启并没有卡住很久，但是也没有（cosy初始化的）错误提示。希望可以给出错误提示到event log中或者解决方案到FAQ中。

感谢解答。

**Comment by HaoboGu** [comment]
> 我重新开了一个idea项目，启动的时候卡住了好久，现在可以给出提示和示例搜索了...

是的，首次安装插件的时候，会下载模型到本地，之后代码提示就完全运行在本地了。后面我们会对错误提示进行优化，感谢反馈~

**Comment by anyuan95** [comment]
抱歉再打扰下，我刚刚切换分支时出现了一个报错。
然后**代码提示和示例搜索就又都不可用了**😭！
希望帮忙看一下如何解决。
[cosy_error_desensitization.log](https://github.com/alibaba-cloud-toolkit/cosy/files/7795581/cosy_error_desensitization.log)

**Comment by HaoboGu** [comment]
理论上重启IDE都可以解决。。 要不再试一下重启IDE？

**Comment by HaoboGu** [comment]
这个报错确实是bug，我们记录下来了，下个版本修复~

**Comment by anyuan95** [comment]
> 理论上重启IDE都可以解决。。 要不再试一下重启IDE？

确实。。。重启大法好

**Comment by zxdxjtu** [comment]
经排查，是IDEA在文件切换（包括git切换，分支切换等），缓存树(StubTree)未及时清理和更新导致。请问这是偶现的问题吗。一般情况下这种问题可以通过重启或者Invalidate Caches & Restart方式恢复。

**Comment by anyuan95** [comment]
> 经排查，是IDEA在文件切换（包括git切换，分支切换等），缓存树(StubTree)未及时清理和更新导致。请问这是偶现的问题吗。一般情况下这种问题可以通过重启或者Invalidate Caches & Restart方式恢复。

这个问题我用的时候还是比较频繁的，也可能是因为我要频繁切换分支才有的出现频率很高的错觉。
我通过重启的方式解决了，重启之后就能正常提供提示和搜索了（不过频繁切换分支还是会触发异常）。
