### ISSUE TITLE
打开代码搜索出现乱码

### ISSUE THREAD

**Issue by CoderXGC** [alibaba-cloud-toolkit/cosy#28]
![Uploading QQ截图20211231134904.png…]()

**Comment by liulhdarks** [comment]
请问你的操作系统是什么

**Comment by liulhdarks** [comment]
我们更新了一下相关文案，如果方便的话，麻烦24小时之后重启一下IDE看看

**Comment by effynku** [comment]
你好(｡･ω･｡)ﾉ搜索页面乱码问题已完成修复，预计下下周可以发布完成～
已经完成修复的离线包获取方式：稚酣🐨 invites you to join DingTalk group chat 阿里云智能编码插件内测用户群, please click to see details. https://h5.dingtalk.com/circle/healthCheckin.html?dtaction=os&corpId=dingd806cd57c1bbb0b33934ee76986e8c23&e2547f07-fd70=231c59f7-60c4&cbdbhh=qwertyuiop
