### ISSUE TITLE
代码示例搜索窗口乱码

### ISSUE THREAD

**Issue by whcrow** [alibaba-cloud-toolkit/cosy#29]
环境：Windows 11，IDEA2021.3.1，cosy0.9.6-beta

![image](https://user-images.githubusercontent.com/7884972/147809901-52278f32-9f71-4d21-90ab-4eba1e9b9f8d.png)

**Comment by liulhdarks** [comment]
麻烦提供一下~/.cosy/tmp/light-cosy-search-default-panel-text.html 文件的内容

**Comment by whcrow** [comment]
> 麻烦提供一下~/.cosy/tmp/light-cosy-search-default-panel-text.html 文件的内容
[light-cosy-search-default-panel-text.zip](https://github.com/alibaba-cloud-toolkit/cosy/files/7795608/light-cosy-search-default-panel-text.zip)

**Comment by liulhdarks** [comment]
我们更新了一下相关文案，如果方便的话，麻烦24小时之后重启一下IDE看看

**Comment by whcrow** [comment]
> 我们更新了一下相关文案，如果方便的话，麻烦24小时之后重启一下IDE看看

简单粗暴，哈哈，Happy New Year!
