### ISSUE TITLE
[FEAT] 代码提示关键词自动加空格

### ISSUE THREAD

**Issue by miss170524** [alibaba-cloud-toolkit/cosy#30]
使用代码提示提供的代码输入后少一个空格,有点难受,望改进,感谢

**Comment by liulhdarks** [comment]
方便提供一下截图和代码上下文吗

**Comment by miss170524** [comment]
![QQ截图20211231164300](https://user-images.githubusercontent.com/95680614/147813076-683e5d85-9ecd-4f53-8056-4920c04b5cb3.jpg)
![QQ截图20211231164358](https://user-images.githubusercontent.com/95680614/147813078-33b7b275-cef5-442c-902a-a409a23fc060.jpg)

**Comment by liulhdarks** [comment]
多谢反馈，建议收到，我们会纳入后续的改进中（PS：今天发布了0.9.6-beta版本，建议升级到最新版本体验）

**Comment by zxdxjtu** [comment]
**0.10.1-beta**版本正式上线啦，对您提到的空格问题做了优化。另外这个版本增加了StackOverflow问答搜索，可以在插件内部通过API或中英文自然语言描述搜索问答，欢迎体验。
