### ISSUE TITLE
无法进行搜索和提示

### ISSUE THREAD

**Issue by yunximing** [alibaba-cloud-toolkit/cosy#31]
![image](https://user-images.githubusercontent.com/73344039/148001733-2ba184a2-5978-47a9-8e46-5d708456f69a.png)
系统版本
     win10
     idea 2021.3

**Comment by Yuyang105** [comment]
你好，请先升级插件至最新版本。

如果升级至最新版本后问题仍未解决，你按照以下步骤来帮助我们排查问题：

在IDE最上方的菜单栏中点击Help，选择Show Log in Explorer/Finder
上传idea.log文件到本页面
打开~/.cosy/logs，上传cosy.log和cosy-local.logxxx至本页面
谢谢！

**Comment by yunximing** [comment]
![image](https://user-images.githubusercontent.com/73344039/148181748-ce4dae3d-9b8a-4654-a399-64676d839b4b.png)
![image](https://user-images.githubusercontent.com/73344039/148181823-b26a91d3-b7d8-4bfc-a6ba-534a43e46c3f.png)

**Comment by HaoboGu** [comment]
从日志看，代码补全功能是正常的。搜索功能麻烦  @Yuyang105 看下

**Comment by Yuyang105** [comment]
哈喽，可以直接上传 ~/.cosy/logs/cosy.log 文件么

上面截图信息太少了，里面没有触发搜索相关的日志

**Comment by yunximing** [comment]
[2021-01-05.log](https://github.com/alibaba-cloud-toolkit/cosy/files/7813371/2021-01-05.log)

**Comment by Yuyang105** [comment]
客户端日志也没看出什么问题，请问你是每次必现么？可以麻烦再麻烦你触发一两次搜索，然后把idea的日志发一下么

idea菜单栏的 Helper-> Show Log in Explorer，idea.log 文件

**Comment by yunximing** [comment]
[2022-01-06.log](https://github.com/alibaba-cloud-toolkit/cosy/files/7818604/2022-01-06.log)
![image](https://user-images.githubusercontent.com/73344039/148309872-d2560db1-2fe8-4482-9c7b-9547f146fc74.png)
我把插件禁用，重新启用就可以使用了

**Comment by Yuyang105** [comment]
有点离奇，没有复现出来。我先把issue关了，后面还有任何问题随时联系我们。
