### ISSUE TITLE
代码实例搜索窗口乱码

### ISSUE THREAD

**Issue by FEINIAO233** [alibaba-cloud-toolkit/cosy#32]
环境：Windows 11，IDEA2021.3.1，cosy0.9.6-beta
![image](https://user-images.githubusercontent.com/38801933/148004987-94f33681-6589-4f96-937c-774c04df04ea.png)

**Comment by effynku** [comment]
您好，感谢您的反馈(｡･ω･｡)ﾉ
很抱歉给您带来不好的使用体验，我们会在本周对win11系统版本常见的字体适配问题做紧急修复，到时发布完成后也会再次通知到您喔。

**Comment by effynku** [comment]
当前有一版已经完成热修复的离线插件，如果愿意提前体验的话可以加一下我们的内测钉钉群：稚酣🐨 invites you to join DingTalk group chat 阿里云智能编码插件内测用户群, please click to see details. https://h5.dingtalk.com/circle/healthCheckin.html?dtaction=os&corpId=dingd4963f2de3530bf19eacd565504e6d8d&70d374=1e70a6&cbdbhh=qwertyuiop
