### ISSUE TITLE
今天莫名出来两次错误.第一次我没记录,这是第二次,也没注意到是社么场景出来的

### ISSUE THREAD

**Issue by miss170524** [alibaba-cloud-toolkit/cosy#35]
![QQ截图20220108121120](https://user-images.githubusercontent.com/95680614/148631019-93fd5841-46aa-4c94-bd94-972972fb03c7.jpg)

**Comment by zxdxjtu** [comment]
感谢反馈～首先想确认下此类报错是否影响插件的正常使用。
我们目前也已知一些此类问题，主要是由于当IDEA工程关闭时，一些插件的异步处理仍未完全结束导致，**暂未发现有影响功能的情况发生**，我们正在和JetBrains官方社区积极寻求修复方法，您可以暂时忽略此类报错。
