### ISSUE TITLE
[bug]快捷键无效

### ISSUE THREAD

**Issue by FMX** [alibaba-cloud-toolkit/cosy#36]
OS:macOS Monterey
IDEA 2021.3.1

command+shift+s 
快捷键不能生效。

**Comment by HaoboGu** [comment]
你好，在当前的设置下，当光标处于无法解析的位置的时候，使用快捷键不会自动触发搜索。这个问题我们已经在尝试解决了，预计下个版本会修复，届时欢迎更新体验 😄
