### ISSUE TITLE
代码示例搜索框中文乱码

### ISSUE THREAD

**Issue by winsee** [alibaba-cloud-toolkit/cosy#37]
![image](https://user-images.githubusercontent.com/11781451/149315043-31abe8b4-14cf-44f2-ae34-df1ac9379443.png)

**Comment by HaoboGu** [comment]
这个问题在内测版已经修复了，会在下周的新版本正式上线，届时更新一下插件版本即可~您可以尝试在编辑区右键，手动触发一下代码搜索。

**Comment by winsee** [comment]
请问下个版本会修复不能通过idea代理联网的问题吗

**Comment by HaoboGu** [comment]
下个修复我们会发布一个离线包，其中包含代码智能补全的所有内容，可以直接离线使用。但是代码搜索现在还不可以通过IDEA代理联网搜索 😞 

这个功能在技术上有些难度，我们也在积极地尝试解决。如果有新的进展我们会即时通知的哈~

**Comment by zxdxjtu** [comment]
中文乱码问题已修复
