### ISSUE TITLE
安装成功无法智能补全也没有提示

### ISSUE THREAD

**Issue by deaidai** [alibaba-cloud-toolkit/cosy#38]
![Snipaste_2022-01-14_13-49-53](https://user-images.githubusercontent.com/97717748/149458418-fb5be479-72df-41f5-b3dd-798a2f2979bb.png)

**Comment by HaoboGu** [comment]
请问搜索有结果嘛？如果有的话，可以尝试一下重启IDE然后稍等一会。这是因为首次安装插件的时候，代码智能补全会下载深度学习模型到本地，之后代码提示就完全运行在本地了

如果重启之后还是不行，你按照以下步骤来帮助我们排查问题：

在IDE最上方的菜单栏中点击Help，选择Show Log in Explorer/Finder
上传idea.log文件到本页面
打开~/.cosy/logs，上传cosy.log和cosy-local.logxxx至本页面
谢谢！

**Comment by bingxueai123456** [comment]
[idea.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8128855/idea.log)
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8128856/cosy.log)
@HaoboGu 我的也不行

**Comment by HaoboGu** [comment]
@bingxueai123456 看起来像是没有网络。Cosy在第一次启动的时候，需要网络连接下载模型，之后才可以离线使用代码智能补全。如果你的机器无法连接公网的话，可以尝试下载all-in-one的插件手动安装，链接在此：https://toolkit.aliyun.com/idea/cosy-intellij-beta-latest-all-in-one.zip

安装方式可以参考：https://alibaba-cloud-toolkit.github.io/cosy/#/zh-cn/guide/quickstart

**Comment by bingxueai123456** [comment]
@HaoboGu 可以连接上公网，没有限制，我的idea也没有开代理，cosy这个插件就是从plugins市场下载的

**Comment by HaoboGu** [comment]
@bingxueai123456 如果是这样的话，应该是一个bug，我新开了一个[issue](https://github.com/alibaba-cloud-toolkit/cosy/issues/47)追踪这个bug。你可以先尝试一下all-in-one的安装包是否可用~

**Comment by bingxueai123456** [comment]
好的

**Comment by bingxueai123456** [comment]
@HaoboGu 离线还是不行，idea缓存我都清了，也重启了
[idea.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8129428/idea.log)
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8129433/cosy.log)
。

**Comment by HaoboGu** [comment]
@bingxueai123456 麻烦移步https://github.com/alibaba-cloud-toolkit/cosy/issues/47

**Comment by zxdxjtu** [comment]
已新开issue跟踪，本issue先关闭了

**Comment by sbysg** [comment]
一样，突然没提示了，倒是 一输入就显示 在更新
