### ISSUE TITLE
本插件和CSDN的插件冲突

### ISSUE THREAD

**Issue by Cities2000** [alibaba-cloud-toolkit/cosy#40]
idea 2021.3.1，安装有csdn工具插件，再安装此插件后，此插件回覆盖边栏上的csdn插件的图标和工具栏上的图标，且图图标会被放大。
![image](https://user-images.githubusercontent.com/25782778/151015257-ca1a942c-0976-4719-8397-2a1c096c304a.png)
![image](https://user-images.githubusercontent.com/25782778/151015489-b9c5bd0d-9955-4170-a10a-912ad9e75e32.png)

**Comment by Cities2000** [comment]
![image](https://user-images.githubusercontent.com/25782778/151015427-9e07996a-0b9a-45d9-abdb-41e8d4ba8a3b.png)

**Comment by zxdxjtu** [comment]
感谢反馈，我们尝试复现下。CSDN的插件名字是叫“CSDN tools”吗？

**Comment by zxdxjtu** [comment]
另外请问下Cosy的版本是最新的吗，麻烦提供下版本号。如果GitHub issue讨论不方便的话，可以进群与我们交流。
![image](https://user-images.githubusercontent.com/9382205/151094174-dde338e5-72e8-43aa-ac26-1a81960cf5da.png)

**Comment by Cities2000** [comment]
> 感谢反馈，我们尝试复现下。CSDN的插件名字是叫“CSDN tools”吗？

是的，cosy是市场安装的0.9.7-beta，csdn tools版本是1.3.2

**Comment by zxdxjtu** [comment]
现象没能复现，从代码层面初步查明是双方插件的logo icon文件路径相同，可能是IDEA加载机制导致的载入冲突，我们正在像社区反馈。下个版本我们会对icon文件重命名，从Cosy插件的角度尽量避免与其他插件的重名问题。

**Comment by zxdxjtu** [comment]
**0.10.1-beta**版本正式上线啦，针对您反馈的问题，我们优化了图片初始大小以及修改路径避免与其他插件冲突，希望能够解决你提的问题。另外这个版本增加了StackOverflow问答搜索，可以在插件内部通过API或中英文自然语言描述搜索问答，欢迎体验。
