### ISSUE TITLE
代码提示问题

### ISSUE THREAD

**Issue by hanelalo** [alibaba-cloud-toolkit/cosy#41]
## 集成开发环境
Intellij IDEA 2021.2.3（Ultimate Edition）

## cosy 插件版本
0.9.6-beta

## 问题

因为 idea 里面新建类的模板是默认不带 `public` 关键字的，比如新建一个 User 类：
```java
class User {

}
```
新建之后，如果想要再手动加上 `public` 时，由 cosy 提供的代码提示有三项：
1. public
2. public class
3. public interface

这里我认为有 2 个问题：
1. 我选择第 1 个代码提示后，代码变成了：
```java
publiclass User {

}
```
对于这个问题，比较奇怪，少了一个 `c` 和空格，导致语法错误。

2. 选择第 3 个代码提示后，代码变成了：
```java
public interfaceclass User {

}
```
对于这个问题，我个人觉得，我代码写的 class，为啥还要提示 `public interface` 呢？而且我选了之后代码语法还是错的。

**Comment by HaoboGu** [comment]
第一个问题应该是一个bug，属于在做向后覆盖的时候的逻辑没有考虑完整。在后面的版本中，对于class、public、interface、private等这些java keywords，我们会在后面自动追加一个空格，并且优化向后覆盖的逻辑，从而解决这个这个问题。

第二个问题，`public interface`这个选项不应该出现的，我们需要对语法过滤的逻辑再做进一步的完善，把这些语法错误的选项都给过滤掉。

非常感谢您的反馈，祝您新春快乐，万事如意~  🎉

**Comment by zxdxjtu** [comment]
**0.10.1-beta**版本正式上线啦，针对您提的问题，做了补充空格等一系列优化。另外这个版本增加了StackOverflow问答搜索，可以在插件内部通过API或中英文自然语言描述搜索问答，欢迎体验。
