### ISSUE TITLE
同时安装本插件和kite，智能补全列表中cosy的图标会放大

### ISSUE THREAD

**Issue by user599** [alibaba-cloud-toolkit/cosy#44]
同时安装kite(1.9.4)和cosy(0.9.7)，那么智能补列表中cosy的图标会放大
1.同时开启
![image](https://user-images.githubusercontent.com/41457884/153968640-8da3244e-81d1-4b0c-a788-e0005e481f2b.png)
2.关闭kite
![image](https://user-images.githubusercontent.com/41457884/153968850-478c0ac5-474a-4a2b-a5b0-f4fc0e1940fb.png)

**Comment by zxdxjtu** [comment]
感谢反馈，目前暂时在本机没能复现，之前遇到过类似的图标缩放问题，怀疑是图标的路径与其它插件冲突导致，下个版本我们会优化下图标存放路径，尽量避免路径冲突。

**Comment by zxdxjtu** [comment]
**0.10.1-beta**版本正式上线啦，针对您反馈的问题，我们优化了图片初始大小以及修改路径避免与其他插件冲突，希望能够解决你提的问题。另外这个版本增加了StackOverflow问答搜索，可以在插件内部通过API或中英文自然语言描述搜索问答，欢迎体验。
