### ISSUE TITLE
[BUG] idea为啥安装cosy插件之后 左下角有一个很大的cosy插件图标？怎么去掉？

### ISSUE THREAD

**Issue by hezhuoyukuai** [alibaba-cloud-toolkit/cosy#46]
**Describe the bug（描述您遇到的问题）**
为啥安装cosy插件之后 左下角有一个很大的cosy插件图标？怎么去掉？

**To Reproduce（复现步骤）**

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/33505007/154218951-55595289-12f1-4ef1-a76a-21cb06008ff2.png)

**本地系统**
 - OS: [e.g. windows10]
 - Cosy Version [e.g. 0.9.7-beta]

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
976491153@qq.com

**Comment by zxdxjtu** [comment]
这个问题最近有收到其他用户的反馈，怀疑是图标路径与其它插件冲突引起的，下个版本会改变图标路径，避免冲突。
