### ISSUE TITLE
[BUG]打开代码示例搜索时，工作区用逗号无法提示

### ISSUE THREAD

**Issue by darkjune** [alibaba-cloud-toolkit/cosy#49]
**Describe the bug（描述您遇到的问题）**
打开代码示例搜索时，工作区用逗号无法提示
关闭搜索页面后， 工作区代码提示恢复正常

**To Reproduce（复现步骤）**

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/3335076/155705302-df9578a5-088f-4100-abc8-fcb2e2a042f3.png)

**本地系统**
 - OS: [e.g. MacOS]
 - Cosy Version [e.g. 0.9.7-beta]

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
darkjune@qq.com

**Comment by zxdxjtu** [comment]
您好，我们已经发布了0.10.2-beta版本，对这个问题进行了修复，欢迎体验

**Comment by darkjune** [comment]
感谢
