### ISSUE TITLE
[BUG] 编码插件搜索没有结果，查看cosy.log发现报错信息是这个Retry failed, won't use BadgerDB this time

### ISSUE THREAD

**Issue by ChengyangLei** [alibaba-cloud-toolkit/cosy#50]
**Describe the bug（描述您遇到的问题）**
编码插件搜索没有结果，查看cosy.log发现报错信息是这个Retry failed, won't use BadgerDB this time

**To Reproduce（复现步骤）**
发现问题后，更新插件，问题没有解决。清除idea 的cache重启也没有得到解决。

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/13332298/156096020-8b10ac90-782c-43cc-b34e-416c69de1597.png)

**本地系统**
 - OS: [e.g. MacOS]
 - Cosy Version [e.g. 0.9.7-beta]

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8158458/cosy.log)

**Comment by HaoboGu** [comment]
理论上这个报错应该不会影响正常功能的使用，你可以尝试一下删除 C:\Users\用户名\.cosy，然后重启IDE，应该可以解决问题

**Comment by ChengyangLei** [comment]
> 理论上这个报错应该不会影响正常功能的使用，你可以尝试一下删除 C:\Users\用户名\.cosy，然后重启IDE，应该可以解决问题

谢谢，按照你的方法，已经解决了，可以正常使用了
