### ISSUE TITLE
无法显示示例代码[BUG]

### ISSUE THREAD

**Issue by MTShi** [alibaba-cloud-toolkit/cosy#51]
**Describe the bug（描述您遇到的问题）**
idea2021.1.3

**To Reproduce（复现步骤）**

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/37536311/156394062-187890d3-ab90-447a-8b9b-874cad2b9f12.png)

**本地系统**
 - OS: [e.g. MacOS]
 - Cosy Version [e.g. 0.9.7-beta]

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
请问网络是正常的吗？
另外麻烦提供下cosy的日志信息方便排查，
MacOS: ~/.cosy/log/cosy.log
Windows: C:\Users\你的用户名\.cosy\log\cosy.log

**Comment by zxdxjtu** [comment]
需要更多信息排查，如果仍有问题欢迎通过钉钉群与我们沟通解决。:)
![image](https://user-images.githubusercontent.com/9382205/160043260-40396869-f586-4977-b798-765dac4056c5.png)
