### ISSUE TITLE
[FEAT]可以代码补全做一个开关吗？想用代码搜素，但是代码补全太卡了

### ISSUE THREAD

**Issue by MoneyloveSSS** [alibaba-cloud-toolkit/cosy#53]
**Please describe the feature you request（请描述您的需求）**

**Describe the solution you'd like （请描述您的解法）**

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by effynku** [comment]
你好～非常抱歉代码补全给你带来了不好的使用体验，我们正在持续努力提升补全性能和降低内存消耗，后续我们也会推出针对电脑配置加载不同的模型的能力，尽可能全面地解决各种情况下的卡顿问题(｡･ω･｡)ﾉ
如果愿意的话，可以提供电脑（硬件与系统版本）、IntelliJ版本和插件版本信息给我们，我们会对卡顿原因进行排查～

**Comment by Dboy233** [comment]
我的笔记本是，mac book air m1的，开启插件后，敲代码都代延迟的。屏幕输出文本跟不上我打字速度。

**Comment by HaoboGu** [comment]
@Dboy233 你好，我们上周发布了最新版本（0.10.1-beta），可以尝试更新一下，看看是否能解决问题。如果不能解决问题的话，您可以把日志（~/.cosy/logs）上传一下，我们排查下问题。另外，我们最近也计划了降低资源消耗和卡顿的工作，请关注插件的更新~

**Comment by HaoboGu** [comment]
@Dboy233 另外，如果是m1的macbook的话，麻烦确认一下IDEA的版本是否也是单独为Apple Silicon编译的。因为使用Intel版本的IDEA默认会调用Intel版本的Cosy，性能会损失50%以上

**Comment by HaoboGu** [comment]
@Dboy233 你这个确实有点奇怪，一般来说不会有这么明显的卡顿才对。可以把~/.cosy/logs下面的日志文件上传一下吗，我们排查下问题

**Comment by Dboy233** [comment]
@HaoboGu
[cosy.log]
[cosy-local.log.2022-03-30.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8401397/cosy-local.log.2022-03-30.log)
[cosy-local.log.2022-03-31.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8401398/cosy-local.log.2022-03-31.log)

(https://github.com/alibaba-cloud-toolkit/cosy/files/8401395/cosy.log)
[cosy-local.log.2022-03-28.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8401396/cosy-local.log.2022-03-28.log)
[cosy-local.log.2022-04-02.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8401400/cosy-local.log.2022-04-02.log)

**Comment by HaoboGu** [comment]
@Dboy233 收到，我们排查一下

**Comment by HaoboGu** [comment]
@Dboy233 初步排查是某些情况下本地推理服务会hang住，确认是一个bug。。 我们在 issue #60 追踪这个问题
