### ISSUE TITLE
[FEAT] 补全内容大小写问题

### ISSUE THREAD

**Issue by virus-plus** [alibaba-cloud-toolkit/cosy#54]
**Please describe the feature you request（请描述您的需求）**
当我需要提示代码出现get方法时，get后面的字段名首字母应该大写，有时候出来的是小写

**Describe the solution you'd like （请描述您的解法）**

get后面的字段名首字母应该大写（驼峰）
**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
18740941410

**Comment by HaoboGu** [comment]
你好，是不是这种例子：
```java
// 期望的结果
String var = obj.getVar();

// Cosy当前给出来的结果
String var = obj.getvar();
```
如果是上面这种情况的话，应该是一个bug或者说badcase，我们会记录下来并且在后续的版本修复

**Comment by HaoboGu** [comment]
@virus-plus 你好，请问你本地安装的插件版本是多少呢？

**Comment by zxdxjtu** [comment]
需要更多信息，该问题未能复现，我们在下个版本会强化语法过滤的能力，尽量避免这种情况发生，感谢反馈，如有更多缺陷反馈或需求，欢迎加入钉钉内测群与我们沟通。
今天**0.10.1-beta**版本正式上线啦！增加了StackOverflow问答搜索，可以在插件内部通过API或中英文自然语言描述搜索问答，欢迎体验 :)

![image](https://user-images.githubusercontent.com/9382205/160043494-205613b6-06a9-44d1-9d04-40875a8046d9.png)
