### ISSUE TITLE
[FEAT]修改Cosy可执行文件的路径

### ISSUE THREAD

**Issue by Zre0** [alibaba-cloud-toolkit/cosy#55]
**Please describe the feature you request（请描述您的需求）**
日志文件输出位置只能默认c盘吗，能不能支持修改

**Describe the solution you'd like （请描述您的解法）**

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by HaoboGu** [comment]
你好，请问你是担心后面日志会占用太多磁盘空间吗？还是其他原因不想让日志放在C盘呢？Cosy对过期以及过大的日志有自动清理功能，日志所占用的内存空间最多也不会超过15M，如果是怕后续日志越积越多那其实完全不用担心的 ;)

**Comment by Zre0** [comment]
不只是日志还有c盘自动生成的.cosy文件夹

这个文件夹占用200多M，这个文件夹是只能在C盘的吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月22日(星期二) 上午10:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba-cloud-toolkit/cosy] [FEAT] (Issue #55)





 
你好，请问你是担心后面日志会占用太多磁盘空间吗？还是其他原因不想让日志放在C盘呢？Cosy对过期以及过大的日志有自动清理功能，日志所占用的内存空间最多也不会超过15M，如果是怕后续日志越积越多那其实完全不用担心的 ;)

**Comment by HaoboGu** [comment]
这个文件夹是Cosy的可执行文件所在，目前是只能在C盘。如果想要调整位置的话目前还不支持，如果要支持的话也需要一定的开发时间。这个需求我们先记下了，有进展会在这里同步。

**Comment by zxdxjtu** [comment]
您好，Cosy的0.10.2-beta版本已经发布，我们对Cosy目录的磁盘占用做了大幅优化，欢迎体验

**Comment by Zre0** [comment]
好的，谢谢。希望以后可以出个exe自定义安装版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月22日(星期二) 上午10:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba-cloud-toolkit/cosy] [FEAT] (Issue #55)





 
这个文件夹是Cosy的可执行文件所在，目前是只能在C盘。如果想要调整位置的话目前还不支持，如果要支持的话也需要一定的开发时间。这个需求我们先记下了，有进展会在这里同步。
