### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SmileWB** [alibaba-cloud-toolkit/cosy#56]
**Describe the bug（描述您遇到的问题）**
无法自动提示和显示代码示例

**To Reproduce（复现步骤）**

**Screenshots（截图）**
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8368176/cosy.log)

**本地系统**
 - OS: [e.g. windows]
 - Cosy Version [e.g. 0.10.1-beta]

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
您好，请确认下网络连接是否正常，看日志是没有网络无法下载模型。我们也提供了无网络环境也可以使用补全的离线包，可以通过这个链接下载：https://toolkit.aliyun.com/idea/cosy-intellij-beta-latest-all-in-one.zip

**Comment by SmileWB** [comment]
我转过这个离线的  也一样都不行

**Comment by SmileWB** [comment]
网络肯定是好的呀  不然怎么装插件

**Comment by zxdxjtu** [comment]
您好，能加一下钉钉，我们拉群排查一下吗？现在是两个问题：
1. all-in-one版本安装后无法补全，需要再看一下cosy.log
2. 正常的版本在网络正常的情况下，无法下载模型，我们需要更多信息排查
![image](https://user-images.githubusercontent.com/9382205/160739038-8f9507bc-02bf-47a3-9f94-89b38f4e0bd1.png)

**Comment by HaoboGu** [comment]
问题已经解决，issue我先关闭啦
