### ISSUE TITLE
[BUG] 中文行补全导致进程退出

### ISSUE THREAD

**Issue by chenshuaijieo** [alibaba-cloud-toolkit/cosy#57]
**Describe the bug（描述您遇到的问题）**
安装完成，也显示下载模型，但是自动补全不生效，没有反应

**To Reproduce（复现步骤）**

**Screenshots（截图）**
<img width="542" alt="image" src="https://user-images.githubusercontent.com/35197205/161013616-549e1ef1-ad1d-46d7-9dd1-1d4bade84383.png">

**本地系统**
 - OS: [e.g. MacOS]
 - Cosy Version [e.g. 0.9.7-beta]

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
麻烦发下日志，我们排查一下
Mac用户：~/.cosy/logs
Windows用户：C盘/用户/[用户名]/.cosy/logs

**Comment by chenshuaijieo** [comment]
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8387568/cosy.log)

**Comment by chenshuaijieo** [comment]
代码实例搜索功是可以正常使用，插件重装过一次，还是不生效

**Comment by chenshuaijieo** [comment]
代码示例功能是可以正常使用，插件重装过一次，自动补全还是不生效

**Comment by zxdxjtu** [comment]
能再麻烦提供下同一目录下的cosy-local.log.2022-03-31的日志文件吗

**Comment by chenshuaijieo** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    alibaba-cloud-toolkit/cosy        您好！我已收到您的邮件。        稍等，我把文件上传到Github上        有什么问题随时与我联系和沟通，祝好！2022-03-31
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                陈帅杰
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    On 03/31/2022 18:46，Zhang ***@***.***> wrote： 




能再麻烦提供下同一目录下的cosy-local.log.2022-03-31的日志文件吗



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by chenshuaijieo** [comment]
[cosy-local-2022-03-31.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8388606/cosy-local-2022-03-31.log)

**Comment by zxdxjtu** [comment]
感谢反馈，似乎是一个Bug，我们验证修复一下，争取尽快给你个热修包:)

**Comment by zxdxjtu** [comment]
感谢反馈，似乎是一个Bug，我们验证修复一下，争取尽快给你个热修包:)

**Comment by chenshuaijieo** [comment]
好的，感谢

**Comment by zxdxjtu** [comment]
您好，Cosy的0.10.2-beta版本已经发布，对此做了修复，欢迎体验
