### ISSUE TITLE
是否考虑对变量名称和方法名实现模糊或者驼峰命名简拼匹配

### ISSUE THREAD

**Issue by ZhangErling** [alibaba-cloud-toolkit/cosy#58]
**Please describe the feature you request（请描述您的需求）**
我是用的是Java语言，在调用对象方法时，会经常使用驼峰命名字母简拼调用方法，发现Cosy对此场景并不提供候选，如`jo.gs`匹配`   jsonObject.getStr()`，IDEA内置代码候选会提供准确候选，而Cosy没有候选

**Describe the solution you'd like （请描述您的解法）**

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by HaoboGu** [comment]
你好，你的需求我们已经收到，我们会内部讨论一下可行性~
