### ISSUE TITLE
[BUG] 无法搜索(已提供日志，排查中)

### ISSUE THREAD

**Issue by yunximing** [alibaba-cloud-toolkit/cosy#59]
**Describe the bug（描述您遇到的问题）**

**To Reproduce（复现步骤）**

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/73344039/161187788-90f4a508-c999-421a-9b49-fc654f198534.png)

![image](https://user-images.githubusercontent.com/73344039/161187825-09a9972b-8819-4d91-876f-39c987a1270a.png)
![image](https://user-images.githubusercontent.com/73344039/161187851-b26ab616-69ab-47b5-9539-2206ba69a08f.png)

**System（本地系统）**
 - OS: 
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by Yuyang105** [comment]
哈喽，麻烦提供一下日志信息
Mac用户：~/.cosy/logs
Windows用户：C盘/用户/[用户名]/.cosy/logs

**Comment by yunximing** [comment]
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8394472/cosy.log)

**Comment by effynku** [comment]
用户你好～经过我们排查：
1. 搜索无结果的原因是本地时间和服务端系统时间不一致，于是被网关拦截了➡️需要检查一下本地系统时间是否正常；
2. 补全无结果的原因是当前Cosy现在系统依赖微软的.NET框架（我们正在尽量避免这种依赖），目前需要本地通过以下指令安装一下.NET➡️进入控制面板，进入【程序】，点击【程序和功能】，点击【启动或关闭Windows功能】，勾选【.NET Framework 3.5 (包括.NET 2.0和3.0)】选项，点击OK；
如果未能解决问题或后续有任何建议意见，请随时联系我们～祝开发愉快:-)

**Comment by yunximing** [comment]
![image](https://user-images.githubusercontent.com/73344039/161362767-d73ebc4e-8c8f-4236-b0c4-3b0658ba7ce5.png)
![image](https://user-images.githubusercontent.com/73344039/161362788-8fa8d267-78eb-4a5f-9900-b75fe7c6825e.png)
![image](https://user-images.githubusercontent.com/73344039/161362807-332e5ced-a061-4a04-abf6-b8ee7708da42.png)
调整过了，还是不行

**Comment by Yuyang105** [comment]
辛苦再提供下最新的cosy.log日志

**Comment by yunximing** [comment]
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8402218/cosy.log)

**Comment by Yuyang105** [comment]
@yunximing 从日志看的话，前后两次贴的日志不像是同一台机器的。方便的话可以加下我们的内测钉钉群吗？我单独找你看下现场

![IMG_8683](https://user-images.githubusercontent.com/12386416/162657787-bd85d348-278f-494e-a0ad-74bf6ae83bcf.JPG)

**Comment by zxdxjtu** [comment]
由于需要更多信息，issue先关闭啦，如果有进一步的信息或再次遇到问题，欢迎保留日志，加钉钉群找到我们排查，非常感谢。
邀请你加入钉钉群聊阿里云智能编码插件内测用户群，点击进入查看详情 https://h5.dingtalk.com/circle/healthCheckin.html?dtaction=os&corpId=ding95a43ae0c7b0fc32507795ee3a72e564&04043=11758&cbdbhh=qwertyuiop
