### ISSUE TITLE
没有代码提示，右边的搜索栏可以正常使用

### ISSUE THREAD

**Issue by duckie8** [alibaba-cloud-toolkit/cosy#6]
日志中无明显报错信息

**Comment by HaoboGu** [comment]
你好，请问插件版本是否为0.9.2-beta？

如果是的话，麻烦上传一下~/.cosy/logs/cosy.log日志文件，我这边排查一下问题

**Comment by duckie8** [comment]
> 你好，请问插件版本是否为0.9.2-beta？
> 
> 如果是的话，麻烦上传一下~/.cosy/logs/cosy.log日志文件，我这边排查一下问题

![image](https://user-images.githubusercontent.com/16376759/140700949-1732be92-82f9-4907-a1df-4b3cb9b39a74.png)

是因为少了这个包么

**Comment by HaoboGu** [comment]
请重启一下IDE试试，理论上不应该出现的，是一个bug

**Comment by duckie8** [comment]
> 请重启一下IDE试试，理论上不应该出现的，是一个bug

还是一样的报错

**Comment by HaoboGu** [comment]
可否麻烦看一下，`~/Library/Caches/.cosy` 目录是否为空？

**Comment by duckie8** [comment]
![image](https://user-images.githubusercontent.com/16376759/140704124-22102fc0-f639-4d7a-9abe-cdc528fbb8fd.png)
![image](https://user-images.githubusercontent.com/16376759/140704126-8605d877-2236-4cc9-8c0e-5e292f63745c.png)

**Comment by HaoboGu** [comment]
收到，我们排查一下，会尽快修复这个问题。感谢反馈！

**Comment by duckie8** [comment]
需要多久才能发布新版本的😂

**Comment by HaoboGu** [comment]
本周内哦，由于JetBrains市场审核还需几天时间，所以下周前可以修复~

**Comment by HaoboGu** [comment]
你好，新版本已发布，烦请更新下新版本看一下问题是否还存在~
