### ISSUE TITLE
cosy-local卡住导致补全超时

### ISSUE THREAD

**Issue by HaoboGu** [alibaba-cloud-toolkit/cosy#60]
**Describe the bug（描述您遇到的问题）**

https://github.com/alibaba-cloud-toolkit/cosy/issues/53#issuecomment-1086425736

**To Reproduce（复现步骤）**

**Screenshots（截图）**

**System（本地系统）**
 - OS: 
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by Dboy233** [comment]
还有个问题是，虽然一开始卡一些，这个卡的程度好像跟我用的时间也有关系，IDE使用的时间越久，卡顿的情况就越严重。

**Comment by HaoboGu** [comment]
@Dboy233 是的，从现象上来看，大概用一段时间后，补全服务会卡住，然后所有的请求都会超时所以ide会变卡。这个现象暂时可以通过kill掉Cosy进程解决，我们还在排查服务卡住的根源，有进度会随时更新~

**Comment by Dboy233** [comment]
@HaoboGu  会不会是网络的问题。我这几天才知道，公司的网络屏蔽了很多域名。

**Comment by HaoboGu** [comment]
@Dboy233 理论上不会，因为代码补全在下载完模型之后是完全离线的，不会涉及到网络调用。我们下周会发布新版本0.10.2-beta的内测版，对之前排查到的问题进行修复，应该可以解决你遇到的问题。

内测版安装方式：
1. 在IDEA插件市场 -> Settings Icon -> Manage Plugin Repositories添加https://plugins.jetbrains.com/plugins/alpha/list
2. 搜索Cosy或者Alibaba Cloud AI Coding Assistant下载插件

**Comment by zxdxjtu** [comment]
您好，Cosy的0.10.2-beta版本已经发布，对已知问题做了修复，欢迎体验
