### ISSUE TITLE
在缺乏.NET Framework的无法启动补全

### ISSUE THREAD

**Issue by HaoboGu** [alibaba-cloud-toolkit/cosy#61]
**Describe the bug（描述您遇到的问题）**
当前cosy-local在windows下依赖.Net Framework，如果电脑上缺乏相应依赖则无法启动，日志出现0xc0000135报错

**To Reproduce（复现步骤）**

**Screenshots（截图）**

**System（本地系统）**
 - OS: Windows
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
已修复
