### ISSUE TITLE
cosy的候选字符仅支持30个

### ISSUE THREAD

**Issue by ZhangErling** [alibaba-cloud-toolkit/cosy#62]
**Describe the bug（描述您遇到的问题）**
如一个比较长的变量名称，超过30个字符，例如这个字符串有40长度，而cosy仅支持到30个，变量名称的后半部分会丢失

**To Reproduce（复现步骤）**
定义一个超过30个字符的变量名称，使用cosy触发候选即可

**Screenshots（截图）**

**System（本地系统）**
 - OS: Windows 11
 - Cosy Version: 0.10.1-beta

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by HaoboGu** [comment]
你好，需求已经收到。现在Cosy因为性能的原因限制了补全的长度，后续我们会增加个人设置的调整，允许自定义补全体验~

另外，变量名称后半部分丢失应该是非预期的，我们需要排查一下
