### ISSUE TITLE
cosy好像在Lambda或匿名内部类中不太好使？

### ISSUE THREAD

**Issue by ZhangErling** [alibaba-cloud-toolkit/cosy#63]
**Please describe the feature you request（请描述您的需求）**
我现在Lambda中使用`jsonObject.getStr("")`,必须我调用过一次，第二次调用他才会提示，代码仅举例，不具有特殊性
即使是同一个方法中的不同Lambda，上一个Lambda已经调用过几遍了，在这个Lambda中他第一次也不提示，而IDEA内置在第一次调用后下次就会提示了，cosy是否是因为过度智能，过于依赖训练，而将使用频次权重设置过低，或者时没有去【识别或学习】用户输入的IDEA的候选项，

通过Lambda猜测匿名内部类中使用也会是同样结果，没有去测试

**Describe the solution you'd like （请描述您的解法）**

也许可以将同方法内相同代码段使用频次权重设置更高一些，在没有更好的结果情况下，推荐本方法或者本类中其他方法已经调用的代码，这样对于本质上是复读机的工具人来说会更友好一些，能很大程度减轻重复性的工作轻度
一点小想法，毕竟IDEA已经有一些基础功能了，这样做带来的利弊可能需要开发团队取舍

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
感谢深度体验和有价值的反馈，工程内的特征学习我们也在尝试加入，使补全内容更加贴近用户工程代码。
