### ISSUE TITLE
All in one 包可以在公司内网环境使用么？是否是相同的效果？

### ISSUE THREAD

**Issue by soyio** [alibaba-cloud-toolkit/cosy#64]
Please describe the feature you request（请描述您的需求）
因为需要在公司内网环境使用，与互联网不通，请问All in one包能够在内网使用，且保有所有功能么？

**Comment by HaoboGu** [comment]
你好，all-in-one的包的代码补全功能在内网是可以正常使用的，而代码搜索是需要连接互联网使用的
