### ISSUE TITLE
使用插件没有办法自动导入类

### ISSUE THREAD

**Issue by GCGH159** [alibaba-cloud-toolkit/cosy#66]
**Describe the bug（描述您遇到的问题）**

**To Reproduce（复现步骤）**

**Screenshots（截图）**

![image](https://user-images.githubusercontent.com/75965109/161599198-90f969f9-2d34-41a4-8b83-f21ca1df34f0.png)

**System（本地系统）**
 - OS: 
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by GCGH159** [comment]
还有就是我使用的idea是2020.2版本的

**Comment by zxdxjtu** [comment]
亲，我们插件做了自动导入的功能，机制是在补全后，通过IDEA内部的引用提示（即alt+Enter）来触发自动引用。如果只有一个引用候选项则自动引用，如果有多个引用候选项则弹出列表供用户选择。
而在实际使用过程中，由于补全的耗时、IDEA内部索引缓慢，自动引用检索速度慢，一行出现多个可引用对象等场景和问题时，自动引用会被跳过或者触发不及时。我们会再努力强化这个功能，尽量召回引用场景，亲可以再多试试，比如`List list = new ArrayList<>();`这样的代码能否自动引用。感谢您的理解和反馈
