### ISSUE TITLE
代码不自动补全

### ISSUE THREAD

**Issue by l280900756** [alibaba-cloud-toolkit/cosy#68]
**Describe the bug（描述您遇到的问题）**

填写代码不自动补全
**To Reproduce（复现步骤）**

**Screenshots（截图）**

**System（本地系统）**
 - OS: 
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
哈喽，麻烦提供一下日志信息
Mac用户：~/.cosy/logs
Windows用户：C盘/用户/[用户名]/.cosy/logs

另外问下搜索正常吗，用的是什么操作系统

**Comment by l280900756** [comment]
不正常，windows操作系统





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba-cloud-toolkit/cosy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月6日(星期三) 中午11:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba-cloud-toolkit/cosy] 代码不自动补全 (Issue #68)





 
哈喽，麻烦提供一下日志信息
 Mac用户：~/.cosy/logs
 Windows用户：C盘/用户/[用户名]/.cosy/logs
 
另外问下搜索正常吗，用的是什么操作系统

**Comment by zxdxjtu** [comment]
麻烦提供一下日志信息呢
在： C盘/用户/[用户名]/.cosy/logs

**Comment by l280900756** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba-cloud-toolkit/cosy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月6日(星期三) 下午2:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba-cloud-toolkit/cosy] 代码不自动补全 (Issue #68)





 
麻烦提供一下日志信息呢
 在： C盘/用户/[用户名]/.cosy/logs

**Comment by l280900756** [comment]
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8424268/cosy.log)

**Comment by l280900756** [comment]
[logs.zip](https://github.com/alibaba-cloud-toolkit/cosy/files/8424273/logs.zip)

**Comment by zxdxjtu** [comment]
麻烦再提供下idea的日志呢，在工具栏的Help>Show log in Finder
![image](https://user-images.githubusercontent.com/9382205/161928953-62492e8b-ae82-416c-9f0c-f38b5727d9c4.png)

BTW，我看有好多天的日志，从3月底安装开始一直都没有搜索和补全结果吗，还是突然某一天失效了？

**Comment by l280900756** [comment]
下载当天是可以用的但是，后来第二天就忽然不能用了，然后现在我的已经好了，把放你给我log文件的地址的.cosy删除从下载插件就可以使用了。然后这个邮箱带的附件就是错误的.cosy文件，你可以看一下能不能找出bug。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba-cloud-toolkit/cosy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月6日(星期三) 下午4:19
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [alibaba-cloud-toolkit/cosy] 代码不自动补全 (Issue #68)





 
麻烦再提供下idea的日志呢，在工具栏的Help&gt;Show log in Finder
 
 
BTW，我看有好多天的日志，从3月底安装开始一直都没有搜索和补全结果吗，还是突然某一天失效了？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

.cosy.zip (166.66M, 2022年05月06日 16:24 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=066163302c6ea6c6ac55dd201530011c5a035b510b03005215035351011d070101004e525152571e01025154510655025c025b553339331d5b0e10491d4a5a43385c&code=8ac03033

**Comment by zxdxjtu** [comment]
嗯嗯，如果再遇到类似的问题，麻烦提供下idea和cosy的日志。我们下个版本会修复一些已知问题，可能可以解决您之前遇到的未知问题

**Comment by zxdxjtu** [comment]
您好，Cosy的0.10.2-beta版本已经发布，修复了一些已知崩溃问题，并且做了自动重启等补救措施，欢迎体验
