### ISSUE TITLE
变量里总是有尖括号

### ISSUE THREAD

**Issue by duckie8** [alibaba-cloud-toolkit/cosy#7]
![image](https://user-images.githubusercontent.com/16376759/141282741-d578a2dc-c8b0-48ae-82e6-5403ea394a3d.png)

**Comment by HaoboGu** [comment]
哎？这个case有点奇怪。。 

请问可以稳定复现嘛？

**Comment by duckie8** [comment]
有很大的几率会有

**Comment by HaoboGu** [comment]
我们这边尝试复现一下，尽量在下个版本修复~

**Comment by duckie8** [comment]
好哦😀

**Comment by zxdxjtu** [comment]
您好，问题已经修复并发布在0.9.4-beta版本中，插件市场正在审核，目前可以从release中下载本地安装。非常感谢您的反馈～https://github.com/alibaba-cloud-toolkit/cosy/releases/tag/0.9.4-beta
