### ISSUE TITLE
不适配IntelliJ IDEA 2022.1 (Ultimate Edition)

### ISSUE THREAD

**Issue by xiaopenghust** [alibaba-cloud-toolkit/cosy#71]
**Describe the bug（描述您遇到的问题）**
插件不适配IntelliJ IDEA 2022.1 (Ultimate Edition)

**To Reproduce（复现步骤）**

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/3761520/163097485-c5f7ece5-c6f8-4fa9-99c8-b00ebdd28079.png)

**System（本地系统）**
 - OS: 
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by HaoboGu** [comment]
你好，我们会尽快做一下IDEA 2022版本的兼容，争取在四月底的下个版本兼容新版本IDEA 🙇

**Comment by roboslyq** [comment]
我也遇到这个问题了，加油！期待兼容版本

**Comment by zxdxjtu** [comment]
> 我也遇到这个问题了，加油！期待兼容版本

嗯嗯，预计下周会发布内测版兼容，可以加入我们的钉钉群接收最新通知：邀请你加入钉钉群聊阿里云智能编码插件内测用户群，点击进入查看详情 https://h5.dingtalk.com/circle/healthCheckin.html?dtaction=os&corpId=ding95a43ae0c7b0fc32507795ee3a72e564&04043=11758&cbdbhh=qwertyuiop

**Comment by zxdxjtu** [comment]
您好，Cosy的0.10.2-beta版本已经发布，兼容了2022.1版本，欢迎体验
