### ISSUE TITLE
代码不会自动补全，文档收索无返回，不知道是否是内网原因，是否有离线版本

### ISSUE THREAD

**Issue by bernaredwang222** [alibaba-cloud-toolkit/cosy#73]
**Describe the bug（描述您遇到的问题）**

代码不会自动补全，文档收索无返回，不知道是否是内网原因，是否有离线版本

**To Reproduce（复现步骤）**
代码不会自动补全，文档收索无返回，不知道是否是内网原因，是否有离线版本

**Screenshots（截图）**

![image](https://user-images.githubusercontent.com/103708291/163502771-6270f860-6ffd-40de-a9dc-fdf400e7dcfa.png)

**System（本地系统）**

win 10

 - OS: 
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
是没有外网的链接吗？cosy提供了离线版，离线版仅支持补全，搜索还是需要网络联通。
离线版下载地址：http://toolkit.aliyun.com/idea/cosy-intellij-beta-latest-all-in-one.zip

安装启动前麻烦先把cosy目录删除，否则会启动失败（这个问题在下个版本会修复）：
Mac用户：~/.cosy
Windows用户：C盘/用户/[用户名]/.cosy

**Comment by TangTank** [comment]
还有离线版，厉害了
