### ISSUE TITLE
CPU 占用过高

### ISSUE THREAD

**Issue by mailbyms** [alibaba-cloud-toolkit/cosy#76]
**Describe the bug（描述您遇到的问题）**
安装插件后，输入代码都感觉到光标的迟顿
任务管理器显示 cosy 和 cosy-local 共占用 30% 以上的 CPU
电脑：thinkpad x13, amd 4750u, 16GB

**To Reproduce（复现步骤）**

**Screenshots（截图）**

**System（本地系统）**
 - OS: windows 10
 - Cosy Version:  最新版

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
您好，Cosy的0.10.2-beta版本已经发布，对补全的性能和效率做了大幅优化，欢迎体验
