### ISSUE TITLE
打开项目插件就报错

### ISSUE THREAD

**Issue by TangTank** [alibaba-cloud-toolkit/cosy#77]
**Describe the bug（描述您遇到的问题）**
打开项目插件就报错

**To Reproduce（复现步骤）**
打开项目

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/2957333/164226389-3282b03a-5f31-4074-af3f-29850b0ba6c2.png)

**System（本地系统）**
 - OS: Win10 21H1
 - Cosy Version:  [v0.10.2-beta](https://github.com/alibaba-cloud-toolkit/cosy/releases/tag/0.10.2-beta)

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
您好，方便把完整的堆栈复制一份发过来吗

**Comment by zxdxjtu** [comment]
怀疑是解压的时候cosy目录被占用的问题，请问已经解决了吗？如果没有解决的话，可以尝试在进程管理器里找到cosy进程并结束，删除cosy目录，再重新启动IDEA。

Mac用户：~/.cosy/logs
Windows用户：C盘/用户/[用户名]/.cosy/logs

**Comment by TangTank** [comment]
最近停用插件了, 问题是偶尔出现的 ,日志已上传,希望有帮助

**Comment by zxdxjtu** [comment]
您好，我们对unzip的问题做了一些热修，会在下个版本发布，可以通过离线方式安装下我们的热修包，谢谢。
https://codeup-algo.oss-cn-hangzhou.aliyuncs.com/biz/cosy-intellij/hotfix/cosy-intellij-0.10.2-beta-unzip-error-fix.zip
