### ISSUE TITLE
能不能增加个可设置项，可以由用户决定启用哪些功能

### ISSUE THREAD

**Issue by archyly** [alibaba-cloud-toolkit/cosy#78]
能不能增加点配置选项
我暂时只想用代码搜索功能，不想启用智能代码补全。
以及一些个人使用习惯设定，优先使用智能代码还是IDE自身的。
智能代码出现的数量，联想深度等等

**Comment by liulhdarks** [comment]
多谢反馈，这个需求已经在排期迭代中了，请关注后续的版本更新。

**Comment by zxdxjtu** [comment]
您好，感谢反馈，谢谢你对Cosy的支持。我们预计在后续的版本中会增加一些补全相关的定制化配置，如补全个数，联想深度等等，敬请关注。另外今天发布的0.10.2-beta版本，我们大幅优化了补全速度和效率，并且对较短的和原生补全类似的候选项做了降级处理，欢迎体验。
