### ISSUE TITLE
能不能像 copilot 那样，直接显示出来提示，Tab 直接确认呢？

### ISSUE THREAD

**Issue by iunsuccessful** [alibaba-cloud-toolkit/cosy#79]
Boolean result = ....;
System.out.println(|`result);`

比如打完 System.out.println( 直接就把 ·result);· 显示在后面了，按下 Tab 就行了。

这样的体验就很酷。

**Comment by zxdxjtu** [comment]
感谢对我们产品的思考和建议。Cosy目前采用的方式是补全，给多个候选项供用户选择，比较适用于较短的补全长度。Copilot目前采用的是inline suggestion，采用的方式是推荐，更适用于较长多行的补全。我们有在考虑提供更多更长的结果，然后通过inline推荐的方式透出（但这种方式一般需要将代码上传，调用远程模型，速度较慢，500ms+），而目前本地模型推荐出来的短序列可能更适合补全形式一些。另外，我们也在内部做了百人范围的问卷调研，约80%的用户认为虽然inline的模式更加炫酷，但是开发习惯上更习惯补全的形式，不希望有大片段的inline占位来干扰编码。再次感谢反馈，我们会更加完善产品，给用户更好的体验:)

**Comment by meinan** [comment]
inline很适合用在重复性的编码，比如做业务模块开发时MVC各分层间很多只是泛型类不一样，通过注释推导出一长条代码500ms完全在可接受范围，实际使用上Copilot的调用远远高于这个，经常要等个2、3秒，我们团队的人还都感觉比自己敲的快，错误率还低。
关于占位的干扰问题，在做这部分编码时关闭自动提示，通过自定义的快捷键直接呼出整句提示，只要扫一眼检查下是不是自己预期的，编码效率至少能高一倍。 @zxdxjtu

**Comment by zxdxjtu** [comment]
@meinan 您好，建议我们收到了，感谢你提供这么高质量的需求。多行块级远端代码补全也在我们今年的规划之中，不过工作量比较大，短时间暂时不会做，敬请期待～
