### ISSUE TITLE
卸载其他插件的时候会触发cosy的使用反馈

### ISSUE THREAD

**Issue by hanelalo** [alibaba-cloud-toolkit/cosy#8]
* Windows10 专业版
* Idea专业版 
    * Build #IU-212.5457.46
    * Runtime Version: 11.0.12+7-b1504.40 amd64
    * VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

装了 cosy 之后，卸载 idea 的其他插件时，会自动打开浏览器跳转到 https://survey.aliyun.com/apps/zhiliao/BjXmO2C7Q

**Comment by zxdxjtu** [comment]
收到，谢谢反馈，我们已安排修复，会在两周后的新版本上线。

**Comment by zxdxjtu** [comment]
您好，问题已经修复并发布在0.9.4-beta版本中，插件市场正在审核，目前可以从release中下载本地安装。非常感谢您的反馈～https://github.com/alibaba-cloud-toolkit/cosy/releases/tag/0.9.4-beta
