### ISSUE TITLE
列编辑模式不能用

### ISSUE THREAD

**Issue by lldacing** [alibaba-cloud-toolkit/cosy#82]
**Describe the bug（描述您遇到的问题）**
列编辑模式下不能使用，确定后都到最后一行了

**To Reproduce（复现步骤）**
按列编辑多行，出现提示后按tab或enter，完成内容都到了最后一行

**Screenshots（截图）**
![GIF 2022-4-30 18-51-10](https://user-images.githubusercontent.com/43737696/166102672-829c83b1-1968-4b4b-8bc9-ffead6231934.gif)

**System（本地系统）**
 - OS: window11
 - Cosy Version: 0.10.2-beta

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
你好，该问题已经识别并修复，会随着下个版本发布

**Comment by zxdxjtu** [comment]
您好，该问题已修复，在最新的内测版本发布，安装方式：

1⃣️网络顺畅环境直接配置channel在插件市场下载：
点击Preferences -> Plugins -> Settings Icon -> Manage Plugin Repositories, 添加：https://plugins.jetbrains.com/plugins/alpha/list ，在插件市场搜索框内输入【Alibaba Cloud AI Coding Assistant】或者【Cosy】，确认为0.10.3-alpha-20220520版本后即可开始体验～
2⃣️离线包请点击直接下载：http://toolkit.aliyun.com/idea/cosy-intellij-0.10.3-alpha-20220520.zip
