### ISSUE TITLE
用了这个感觉好卡啊，idea内存飙升到4G

### ISSUE THREAD

**Issue by mclubing** [alibaba-cloud-toolkit/cosy#83]

**Comment by mclubing** [comment]
idea:2022.1, jdk:1.8, win10 x64, 内存16G，AMD ryzen5 2600X

**Comment by zxdxjtu** [comment]
能方便发一下内存占用比以及内存消耗趋势图吗？启动的时候会做一下解压和加载缓存的操作，会消耗比较大的内存。
后续由于补全模型推理是在本地，虽然会消耗一些算力，但应该不会消耗过多。

**Comment by zxdxjtu** [comment]
欢迎试一下我们的最新内测版，安装方式如下，我们做了很多性能方面的优化，如果仍然出现问题，欢迎将本地的内存消耗趋势图发我们看一下（idea、cosy、cosyloacal三个进程）

1⃣️网络顺畅环境直接配置channel在插件市场下载：
点击Preferences -> Plugins -> Settings Icon -> Manage Plugin Repositories, 添加：https://plugins.jetbrains.com/plugins/alpha/list ，在插件市场搜索框内输入【Alibaba Cloud AI Coding Assistant】或者【Cosy】，确认为0.10.3-alpha-20220520版本后即可开始体验～
2⃣️离线包请点击直接下载：http://toolkit.aliyun.com/idea/cosy-intellij-0.10.3-alpha-20220520.zip
