### ISSUE TITLE
idea 2020.3 版本 重启idea后一直卡在启动加载界面

### ISSUE THREAD

**Issue by Grey-Castle** [alibaba-cloud-toolkit/cosy#85]
**Describe the bug（描述您遇到的问题）**
idea 2020.3 版本 重启idea后一直卡在启动加载界面，控制台杀掉idea进程后可以启动idea，启动idea后关闭idea然后再次打开还是卡在加载界面，之后又在控制台杀进程启动idea，进入idea后卸载插件，再重启就正常了，不管怎么关闭启动都不会卡住。

**To Reproduce（复现步骤）**
使用idea 2020.3 版本，安装插件，然后重启idea，之后关闭idea，然后在打开idea就会卡在启动加载界面。

**Screenshots（截图）**
关闭idea
![image](https://user-images.githubusercontent.com/43396850/166862486-7d51dc83-b696-4d98-bdfa-d03a7b225ad4.png)
重新打开后，一直卡在启动加载界面
![image](https://user-images.githubusercontent.com/43396850/166861886-298917a5-f1ae-4bf0-b70d-8cff69cb17dd.png)
控制台杀掉进程
![image](https://user-images.githubusercontent.com/43396850/166861996-ae99d500-d0d4-4442-9ff8-9dd5753fc015.png)
之后才能正常启动

**System（本地系统）**
 - OS: windows10
 - Cosy Version: 0.10.2-beta

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
麻烦提供下IDEA的日志，在上方工具栏的Help>Show log in Finder，以及Cosy的日志，在用户目录下的.cosy（Mac用户~/.cosy/logs
Windows用户：C盘/用户/[用户名]/.cosy/logs）这个问题我们会尽快跟进。

**Comment by zxdxjtu** [comment]
可能是版本覆盖的问题，也欢迎试一下我们的热修版本：https://codeup-algo.oss-cn-hangzhou.aliyuncs.com/biz/cosy-intellij/hotfix/cosy-intellij-0.10.2-beta-unzip-error-fix.zip

**Comment by Grey-Castle** [comment]
是用这个版本的可以了
这是日志文件：
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8629075/cosy.log)

**Comment by zxdxjtu** [comment]
IDEA崩溃的问题可能还是需要看下IDEA的日志，上方工具栏的Help>Show log in Finder
希望能将整个log文件夹打包压缩发我看下
![image](https://user-images.githubusercontent.com/9382205/166873177-4fdf4997-1a72-4874-b51d-5370d19746cb.png)

**Comment by Grey-Castle** [comment]
idea的日志文件：
[log.zip](https://github.com/alibaba-cloud-toolkit/cosy/files/8629145/log.zip)

**Comment by zxdxjtu** [comment]
这个unzip的问题我们已经识别到，麻烦通过本地先安装下我们的热修版本：https://codeup-algo.oss-cn-hangzhou.aliyuncs.com/biz/cosy-intellij/hotfix/cosy-intellij-0.10.2-beta-unzip-error-fix.zip
或者可以在启动IDEA前先把cosy进程kill掉，删除.cosy文件夹再启动。
非常抱歉。

**Comment by Grey-Castle** [comment]
好的，谢谢，我先用你们的热修版本

**Comment by zxdxjtu** [comment]
您好，我们的最新内测版已在520发布，该热修已上线。安装方式：

1⃣️网络顺畅环境直接配置channel在插件市场下载：
点击Preferences -> Plugins -> Settings Icon -> Manage Plugin Repositories, 添加：https://plugins.jetbrains.com/plugins/alpha/list ，在插件市场搜索框内输入【Alibaba Cloud AI Coding Assistant】或者【Cosy】，确认为0.10.3-alpha-20220520版本后即可开始体验～
2⃣️离线包请点击直接下载：http://toolkit.aliyun.com/idea/cosy-intellij-0.10.3-alpha-20220520.zip
