### ISSUE TITLE
安装完整离线版，但无提示出现

### ISSUE THREAD

**Issue by luohaoxh** [alibaba-cloud-toolkit/cosy#86]
**Describe the bug（描述您遇到的问题）**

安装好以后，就出现过一次提示，后续再没有出现过。

**To Reproduce（复现步骤）**

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/12394390/167175150-0c26b244-d2d3-4a2c-a9a6-bb9ac84e2ea5.png)

**System（本地系统）**
 - OS: win10
 - Cosy Version: 0.10.2

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
您好，能麻烦提供下.cosy/log/cosylocal 的日志吗

**Comment by luohaoxh** [comment]
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8644776/cosy.log)

附件

**Comment by luohaoxh** [comment]
只有这个cosy日志文件，没有cosylocal

**Comment by zxdxjtu** [comment]
您好，可以参考下我们的FAQ：https://alibaba-cloud-toolkit.github.io/cosy/#/zh-cn/guide/faq?id=q-%e4%bb%a3%e7%a0%81%e8%a1%a5%e5%85%a8%e6%97%a0%e7%bb%93%e6%9e%9c%e6%80%8e%e4%b9%88%e5%8a%9e%ef%bc%9f

**Comment by luohaoxh** [comment]
执行cosylocal.exe有一个窗口一闪而逝，没有其他提示出现。

![image](https://user-images.githubusercontent.com/12394390/167258128-4a997710-7a64-4ae4-9a5e-0f9c2ed7e326.png)

**Comment by zxdxjtu** [comment]
这个问题还是第一次碰到，在命令行能执行这个exe吗？

**Comment by luohaoxh** [comment]
命令行执行也是黑窗口一闪而过

**Comment by HaoboGu** [comment]
> 命令行执行也是黑窗口一闪而过

这个问题很奇怪，可以麻烦你下载一下https://github.com/lucasg/Dependencies ，然后把cosylocal.exe拖进去，看一下依赖的具体详细情况吗？

**Comment by luohaoxh** [comment]
是像下面这样吗？我看都有
![image](https://user-images.githubusercontent.com/12394390/167343848-b2dd2e22-5fd6-4b3b-afd8-78d40a40eb48.png)

**Comment by luohaoxh** [comment]
win10，10.0.17763

![image](https://user-images.githubusercontent.com/12394390/167379713-1ef47643-5149-4eeb-8f44-68b1b13edd01.png)

**Comment by HaoboGu** [comment]
感谢回复，我们会尽快排查相关问题

**Comment by HaoboGu** [comment]
你可以按照如下步骤再尝试排查一下问题：
1. 安装[windbg](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools)
2. 在安装文件夹下面找到 `gflags.exe`，并且启动它
3. 选择`Image File`，然后再Image:后面输入`cosylocal.exe`，按Tab键使其生效 <img width="801" alt="image" src="https://user-images.githubusercontent.com/8640918/168533145-17573f88-d56f-49e4-bb7a-24b588bd3576.png">
4. 选中`Show loader snaps` 
6. 启动`windbg`，并且在windbg中启动`cosylocal.exe`
7. 在命令窗口，输入`g`，然后回车
8. 接下来会有很多日志打出来，搜索`ERROR: Unable to load DLL`可以看到是哪些依赖出了问题

如果你找不到有问题的dll，可以把相关日志上传到这里。

此外，你可以参考https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order。
<img width="869" alt="image" src="https://user-images.githubusercontent.com/8640918/168533958-eeb19f9a-1373-4fe5-b716-012e1f926bfa.png">

在1-4目录中，搜索一下`onnxruntime.dll`是否存在。如果存在，删除之再重试。

**Comment by luohaoxh** [comment]
[01_未删除onnxruntime.dll日志.txt](https://github.com/alibaba-cloud-toolkit/cosy/files/8702974/01_.onnxruntime.dll.txt)

删除文件以后无法加载了

![删除onnxruntime dll](https://user-images.githubusercontent.com/12394390/168669892-69375221-bf30-493d-b8b7-03bb0493cb4c.png)

**Comment by HaoboGu** [comment]
如果onnxruntime.dll只有上面两个的话，应该是不用删除的。
我看了一下windbg的日志，似乎很多dll指向了`C:\Windows\LVUAAgentInstBaseRoot\system32\`下的dll，然后导致dll load失败。这个目录好像不是正常windows的目录，看起来像是dll被劫持了。我这边也没有进一步的解决方案，感觉可能只有重装系统能解决了。。

**Comment by luohaoxh** [comment]
把这些删除了可以吗？
![image](https://user-images.githubusercontent.com/12394390/168768949-996ca0f1-0f67-40ef-bb47-f524daa1bac0.png)

LVUAAgentInstBaseRoot 这个目录应该是公司安装了联软安全监控软件有的，真的木有办法绕过了吗。。。

**Comment by HaoboGu** [comment]
可以尝试一下把上面你标记红框的那几个删除再试一下。我这边再探索一下有没有其他的方案可以绕过LVUAAgentInstBaseRoot下的dll😂
