### ISSUE TITLE
有些注解不能自动import

### ISSUE THREAD

**Issue by GAKKI-fox** [alibaba-cloud-toolkit/cosy#9]
有些注解不能自动import
![image](https://user-images.githubusercontent.com/35187654/141706017-798685f8-112e-4065-a66b-c19a91a24426.png)

**Comment by zxdxjtu** [comment]
请问是什么注解，我们复现一下？代码补全仅会推荐概率最高的候选项，如果没有你想要的话，可以尝试打几个开头字符。

**Comment by zxdxjtu** [comment]
注解的case比较复杂，Cosy也是利用了idea自带的补全能力，与依赖项，上下文环境有关，我们会在开发和使用过程中持续优化，加一些日志，看看能不能召回一部分自动import的case。感谢反馈，由于没能稳定复现，日志信息不充分，我们内部记录下问题，这个issue先关闭了。
