### ISSUE TITLE
安装离线版后，IDEA巨卡，且几乎无提示，CPU直接打满

### ISSUE THREAD

**Issue by timokiller** [alibaba-cloud-toolkit/cosy#91]
**Describe the bug（描述您遇到的问题）**
昨天安装结束后，的确会出现提示，但是随着时间推移，我的thinkPad被降频了, 今天更离谱，CPU直接打满，IDEA卡到爆，idea是2022.1.2 Preview (今天刚更新) cosylocal 运行报错，管理员模式运行一闪而过

**To Reproduce（复现步骤）**

**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/14068572/169281337-39084e50-8f65-4967-b609-8e2bd5abea30.png)
![image](https://user-images.githubusercontent.com/14068572/169281438-69180fd8-5bf8-4724-bc5e-121b38546180.png)

**System（本地系统）**
 - OS: win11
 - Cosy Version: 0.2.6

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by timokiller** [comment]
![image](https://user-images.githubusercontent.com/14068572/169282351-4b94e0c3-9719-470a-a9c4-56d9feb4251b.png)
使用IDEA的时候CPU截图

**Comment by zxdxjtu** [comment]
您好，我们最近发布的内测版本对cosylocal偶发的一些异常以及内存高占用做了修复，麻烦试一下我们的最新内测版本插件呢？安装方式：

1⃣️网络顺畅环境直接配置channel在插件市场下载：
点击Preferences -> Plugins -> Settings Icon -> Manage Plugin Repositories, 添加：https://plugins.jetbrains.com/plugins/alpha/list ，在插件市场搜索框内输入【Alibaba Cloud AI Coding Assistant】或者【Cosy】，确认为0.10.3-alpha-20220520版本后即可开始体验～
2⃣️离线包请点击直接下载：http://toolkit.aliyun.com/idea/cosy-intellij-0.10.3-alpha-20220520.zip

**Comment by zxdxjtu** [comment]
您好，最新的0.10.3-beta版本已发布，包括了上述的内测版修复，欢迎更新
