### ISSUE TITLE
安装后 M1 14 Mac 耗电增加很多

### ISSUE THREAD

**Issue by xtuer** [alibaba-cloud-toolkit/cosy#92]
**Describe the bug（描述您遇到的问题）**
安装后 M1 14 Mac 耗电增加很多，续航减少一半，卸载后恢复正常。

**To Reproduce（复现步骤）**

**Screenshots（截图）**

**System（本地系统）**
 - OS: 
 - Cosy Version: 

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**

**Comment by zxdxjtu** [comment]
您好，能看一下你的进程能耗图吗（IDEA，cosy，cosylocal三个进程），我们看一下具体是哪一块能耗过高。一般情况下，插件在启动的时候会做一下初始化操作能耗会略高，启动完成后，只会对补全、搜索等操作做对应处理。

**Comment by xtuer** [comment]
卸载好久了，今天是看看 VS Code 插件能不能使用了才来 issue 里问问随便提了个问题，IDEA 里不考虑使用了。
Cosy 的代码补全感觉没必要，主要是用来搜索某个功能的实现代码。

**Comment by zxdxjtu** [comment]
请问现在主要的开发工具是vscode吗，在IDEA用的时候也是用代码搜索吗？不知道您之前用的是哪个版本，我们最近5月20日发布了IDEA的内测版本，做了很多性能优化，欢迎尝试一下：http://toolkit.aliyun.com/idea/cosy-intellij-0.10.3-alpha-20220520.zip
如果仍然存在能耗较高的问题，麻烦提供我们一下IDEA，cosy，cosylocal三个进程能耗走势图，我们尽快排查一下。
另外想问下M1上用的IDEA是下载的M1专属版吗，如果下载的是Mac Intel版本，插件也会起Intel版本的进程，中间计算有一层转换，会导致能耗增加。

**Comment by xtuer** [comment]
IDEA 是 Sillicon 版本的，试了下这个版本，安装后会启动 cosy 的 2 个进程，即使不使用或者退出 IDEA 它们也会一直消耗 CPU，大概 0.2%，而不是只是搜索和自动补全的时候，是一直都在使用 CPU。

**Comment by zxdxjtu** [comment]
进程会有一些缓存操作，不过应该能耗不大，0.2%客观上应该属于可接受范围。感谢你的反馈，我们也会持续对用户关心的性能，能耗等问题做优化:)

**Comment by xtuer** [comment]
没注意以前是什么情况，但是不使用的时候也在持续使用 CPU 等感觉还有优化空间。

**Comment by zxdxjtu** [comment]
感谢反馈，那这个issue先关闭啦～我们会在开发过程中注意并优化这些能耗细节
