### ISSUE TITLE
只想要搜索代码的插件或者网页不要自动补全

### ISSUE THREAD

**Issue by xtuer** [alibaba-cloud-toolkit/cosy#97]
**Please describe the feature you request（请描述您的需求）**
只想要搜索代码的插件或者网页不要自动补全，个人不太喜欢太多的自动补全功能。

**Describe the solution you'd like （请描述您的解法）**
希望能提供一个只有搜索代码的插件或者网页，不要代码补全功能，或者提供 API 也可以。

**Contact Info（如愿意请留下联系方式，需求上线后，我们将第一时间联系您）**
邮件：biao.mac@icloud.com

**Comment by zxdxjtu** [comment]
您好，这个需求我们正在评估中，作为开发方我们希望能够将完整的智能编码能力呈现给用户，也理解用户的定制化诉求。下周将发布的0.10.3-beta版本，我们提供了代码补全的个性化配置，您可以将补全条目数设置为1，选择性能优先，最小化地减少代码补全的功能透出。

**Comment by zxdxjtu** [comment]
感谢对代码搜索的喜欢，我们陆续收到过单独关闭补全能力的需求，我们的本意希望持续完善补全的准确度和性能来赢回用户的信任，很遗憾没能做到完美，并且也遇到了一些用户对补全功能本身就不喜欢。经过慎重考虑，我们计划在下个版本增加单独关闭代码补全功能的设置，发布后会在这个issue回复，敬请期待 :)

**Comment by ChenforCode** [comment]
同样不太喜欢不全功能，因为有时补全是错的，而且还放在补全的第一位，这样我还要往下选IDEA的正确补全，很麻烦。但是自己又很喜欢这个代码搜索功能，所以希望可以提供单独关闭代码补全的功能。

**Comment by lldacing** [comment]
我是嫌占内存太严重，已经大半年没用了，这么久了还没加好？太难产了

**Comment by liulhdarks** [comment]
0.10.5-beta版本已经发布，适配2023.1版本，支持代码补全开关，并且修复占用内存过高的问题，请到插件市场或Cosy官网更新
