### ISSUE TITLE
无法搜索代码

### ISSUE THREAD

**Issue by liuxin1221** [alibaba-cloud-toolkit/cosy#98]
[cosy.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8887233/cosy.log)

**Comment by liuxin1221** [comment]
[cosy-local.log](https://github.com/alibaba-cloud-toolkit/cosy/files/8887275/cosy-local.log)

**Comment by zxdxjtu** [comment]
请问你的插件版本是多少？

**Comment by zxdxjtu** [comment]
可以试一下我们最新的内测版本：http://toolkit.aliyun.com/idea/cosy-intellij-0.10.3-alpha-20220520.zip

**Comment by zxdxjtu** [comment]
然后把cosy进程关掉，将~/.cosy目录删除，重启idea

**Comment by liuxin1221** [comment]
可以了，感谢
